Fixed 404 Error On Main Docs Page
json-schema-org/website pull request #1018
Opened 2024-10-12 09:42 UTC by IyaadDev

# Fix: 404 Error On Docs Home Page Contribute Button

Impacted URL: https://json-schema.org/docs

**Issue Number:**
-  Closes #1012 

Just some proposed changes to fix the issue

**Summary**
- Changed url for contribute on github button from https://github.com/json-schema-org/website/blob/main/pages/docs/_index.md (404) to https://github.com/json-schema-org/website/blob/main/pages/docs/index.page.tsx (200)

**Does this PR introduce a breaking change?** No

2024-10-12 09:54 UTC, DarhkVoyd requested changes
Hey, thanks for working on the issue. However, the logic `DocsHelp` component seems about right, you were supposed to fix this reference instead:  https://github.com/json-schema-org/website/blob/cec0d010ec5cf1b163a61955f5a02551d8d47431/pages/docs/index.page.tsx#L10

Removing this prop from passing to the `DocsHelp` component in the `index.page.tsx` file of `docs` will fix the issue without changing the component behaviour.

2024-10-15 07:37 UTC, DarhkVoyd commented
@benjagm Upon reviewing the proposed changes, I found that they break the `DocsHelp` component. I've provided feedback and suggested the appropriate fix in my review. We're currently awaiting the author to implement those changes. Once addressed, I'll re-review to ensure everything is in order.

2024-10-15 07:39 UTC, benjagm commented
> @benjagm Upon reviewing the proposed changes, I found that they break the `DocsHelp` component. I've provided feedback and suggested the appropriate fix in my review. We're currently awaiting the author to implement those changes. Once addressed, I'll re-review to ensure everything is in order.

Thanks DV ♥️.

I missed that the change you requested was still pending.

2024-10-17 08:38 UTC, IyaadDev commented
working on it at the moment

2024-10-17 12:10 UTC, IyaadDev commented
moved to #1031

2024-10-17 12:10 UTC, closed without merging