[Fix]:  Fixed Navbar dark mode navigation
json-schema-org/website pull request #1059
Opened 2024-10-24 05:28 UTC by officeneerajsaini

This Pull Request Fixes the Navbar Navigation Color in Dark mode.

**Issue Number:**
-  Closes #1057 

**Screenshots/videos:**
Before:

https://github.com/user-attachments/assets/eeec6f55-fa84-4c9a-83ee-2658141c4594

After : 

https://github.com/user-attachments/assets/9bcd0f82-f0b8-4259-841b-596bf9390f2a

2024-10-24 05:32 UTC, officeneerajsaini commented
In macOS, I'm encountering another issue with the Navbar search button. The search button's style contains a background-color property.

2024-10-24 05:37 UTC, officeneerajsaini commented
<img width="1440" alt="Screenshot 2024-10-24 at 11 03 04 AM" src="https://github.com/user-attachments/assets/57f4e17d-d605-4ade-9136-4320188c1970">

2024-10-24 06:34 UTC, DhairyaMajmudar commented
> I'm sorry for making this pull request complex for the reviewer. Initially, I did my work well, but the `package-lock.json` and `yarn.lock` files were included. Then I made another commit, and I wanted to combine both commits into a single one. Due to some issues, I deleted my branch and then restored it. Now, I've combined both commits into one, but it also includes the previous merged commit. That's what has been happening with me.

No worries with that just remove the changes from `yarn.lock` and `package.json` files.

2024-10-24 06:35 UTC, officeneerajsaini commented
> > I'm sorry for making this pull request complex for the reviewer. Initially, I did my work well, but the `package-lock.json` and `yarn.lock` files were included. Then I made another commit, and I wanted to combine both commits into a single one. Due to some issues, I deleted my branch and then restored it. Now, I've combined both commits into one, but it also includes the previous merged commit. That's what has been happening with me.
> 
> No worries with that just remove the changes from `yarn.lock` and `package.json` files.

Yeah I did 😄

2024-10-24 06:36 UTC, officeneerajsaini commented
The commit #1049 is also included in my pull request.

2024-10-24 06:41 UTC, DhairyaMajmudar commented on package.json
Seems like there are still some more changes left to be removed : )

2024-10-24 06:41 UTC, DhairyaMajmudar commented on yarn.lock
From here too

2024-10-24 06:50 UTC, officeneerajsaini commented on package.json
What should I do now then, that commit already merged with that code.

2024-10-24 17:19 UTC, officeneerajsaini commented
@DhairyaMajmudar Please Review Code now.

2024-10-25 05:38 UTC, DhairyaMajmudar commented
@officeneerajsaini pls. don't change the font colors

2024-10-25 06:03 UTC, officeneerajsaini commented
> @officeneerajsaini pls. don't change the font colors

In dark mode, some light colors look better than a dark-on-dark combination.

Consistent color:

https://github.com/user-attachments/assets/7fa172a0-1b4d-4dfa-bfe0-1c1f1c9dd76c

Some Lightness :

https://github.com/user-attachments/assets/99eb2397-6a14-4ee3-9945-266d136dfcf8

Should I go with the website theme color?

2024-10-26 07:00 UTC, benjagm requested changes
Looks great, Thanks!!

 However I do prefer the white color for the navbar fonts instead that light grey. Can we change that?

2024-10-26 08:33 UTC, officeneerajsaini commented
> Looks great, Thanks!!
> 
> However I do prefer the white color for the navbar fonts instead that light grey. Can we change that?

Yes, and what about the color for the active and hover effects?

2024-10-30 12:19 UTC, officeneerajsaini commented
https://github.com/user-attachments/assets/9bb68b07-00d7-4f28-8a54-facde004797f

2024-11-06 11:08 UTC, officeneerajsaini commented
@benjagm  now take a look on code

2024-11-08 06:13 UTC, benjagm commented
It looks better. However, the blue color is difficult to distinguish from the background. Can we find something lighter? Why not just underlying the current section instead of changing the color?

2024-11-08 10:42 UTC, officeneerajsaini commented
https://github.com/user-attachments/assets/034906a6-44d7-4623-890c-078fcf5cae46
I chose this color from the hover effect on the 'Star on GitHub' button; it seems to look good.

2024-11-08 12:52 UTC, DhairyaMajmudar commented on styles/globals.css
It seems like this class is no longer used, if it is so you can remove it.

2024-11-08 13:40 UTC, officeneerajsaini commented on styles/globals.css
Dhairya, I changed the grey color to white in response to Benjamin's request.

> Looks great, Thanks!!
> 
> However I do prefer the white color for the navbar fonts instead that light grey. Can we change that?

I also added a new CSS property to show an underline on the current page, so some additional CSS properties need to be added. 😄

2024-11-09 04:21 UTC, officeneerajsaini commented on styles/globals.css
This class is used when there are 6 community meetings, and events are available.

Without class :
<img width="1440" alt="Screenshot 2024-10-23 at 5 00 04 PM" src="https://github.com/user-attachments/assets/589b0bf1-84c4-4994-a1cb-b8c882a4977d">

with class :
<img width="1440" alt="Screenshot 2024-10-23 at 5 02 02 PM" src="https://github.com/user-attachments/assets/67f4c30f-e4eb-4da7-967c-116a34c7975c">

2024-11-09 04:23 UTC, DhairyaMajmudar commented on styles/globals.css
Awsm! With that then keep it don't remove

2024-11-10 07:48 UTC, benjagm commented
Hi everyone.

I checked the current version and found this behavior:
- Light style:
  - Style looks good 
  - When navigating using links in the header, all styles to highlight the current section work with the exception of Tools. When in tools there is no style in the header highlight the current version.
- Drak Style:
  - When navigating using links in the header, the styles to highlight the current version don't work.

2024-11-10 09:33 UTC, officeneerajsaini commented
> * Light style:
>   
>   * Style looks good
>   * When navigating using links in the header, all styles to highlight the current section work with the exception of Tools. When in tools there is no style in the header highlight the current version.

Yes , Found that part too .

2024-11-23 09:07 UTC, benjagm commented
@officeneerajsaini we are very close! Let's make the last change and push it. Great work so far. Thanks for your patience.

2024-12-13 06:59 UTC, benjagm commented
Hi @officeneerajsaini . Is there any update on this?

2024-12-13 14:46 UTC, benjagm commented
Thanks @officeneerajsaini . Ok I think the reason why the preview deployment I checked is outdated is because the deployment work failed due to some format checks: 

https://github.com/json-schema-org/website/actions/runs/11986321387/job/33419247261?pr=1059

Can you run prettier on that file? I am so looking forward to merge it.

thanks for your patience. It has been a very busy weeks for me on my new job.

2024-12-13 17:51 UTC, officeneerajsaini commented
@benjagm Yeah, I know you were very busy at that time, which is why I waited for your response.
I have done everything that was needed. On my local host, everything is working well, but in this preview development, I can't see the underlining navigation.

2024-12-17 13:28 UTC, officeneerajsaini commented
Now This Code Ready To Merge @benjagm Please take a Look.

2024-12-21 15:13 UTC, benjagm approved these changes
Thanks for the hard work Neeraj. I just added a small change to make it work. Kudos!

2024-12-21 15:13 UTC, merged

2024-12-21 16:34 UTC, officeneerajsaini commented
[Thanks,](url) Benja 🫠