fix: Author Rendering at the Blog page
json-schema-org/website pull request #1066
Opened 2024-10-26 10:03 UTC by Ritesh2351235

**What kind of change does this PR introduce?**
Changing the styling in the Blog page to avoid conflicts with the PurgeCSS.

**Issue Number:**
-  Closes #1065

2024-10-26 12:28 UTC, DhairyaMajmudar requested changes
@Ritesh2351235 pls. remove the changes associated with /community folder. Here its used as git submodule thus if you wanna perform any change in it you have to open a PR in https://github.com/json-schema-org/community/  repo

2024-10-26 12:28 UTC, DhairyaMajmudar commented on _includes/community
Pls. remove changes from here

2024-10-26 16:47 UTC, Ritesh2351235 commented
@DhairyaMajmudar @benjagm 
Hey Benja, I'm actually stuck on this problem. I tried avoiding string concatenation and adding a safelist to the Tailwind config files. Are there any other ways I could solve this problem?

2024-10-26 17:25 UTC, Ritesh2351235 commented
@DhairyaMajmudar I think the changes are working fine now.

2024-10-27 09:20 UTC, DhairyaMajmudar commented
@Ritesh2351235 is earlier commit the changes were related to some other lines of code. Can you pls. check that.

2024-10-27 09:25 UTC, Ritesh2351235 commented
@DhairyaMajmudar I have removed that changes there was a problem while rebasing the repo 
Now I have only updated the blog page

2024-10-28 06:13 UTC, Ritesh2351235 commented
@DhairyaMajmudar Can you just check with the production code theater the authors are rendering correctly in the blog page?
Let me know if any changes are required.

2024-10-28 07:42 UTC, DhairyaMajmudar reviewed
```tsx
className={`
                                      bg-slate-50
                                      rounded-full
                                      -ml-3
                                      bg-cover
                                      bg-center
                                      border-2
                                      border-white 
                                      ${sizeClass}`}
```

2024-10-28 07:45 UTC, DhairyaMajmudar commented
> @DhairyaMajmudar Can you just check with the production code theater the authors are rendering correctly in the blog page? Let me know if any changes are required.

True @Ritesh2351235 on production website the bug is now not showing but its seems like the bug mentioned arises in some special cases. The styles affecting the authors' images are joined using array methods which is quite strange. 
Let's replace them with the string literals as I've shown in this comment https://github.com/json-schema-org/website/pull/1066#pullrequestreview-2398167388

2024-11-08 06:10 UTC, benjagm commented
I think the styles are not working because of the Tailwind styles purge process. Specifically, we should avoid using string concatenation to create class names:

https://v2.tailwindcss.com/docs/optimizing-for-production#writing-purgeable-html


See https://github.com/json-schema-org/website/pull/1029#pullrequestreview-2379320382

2024-11-13 04:14 UTC, Ritesh2351235 commented
@DhairyaMajmudar Went through all the Documentation and this should solve the problem now !!

2024-12-13 07:08 UTC, DhairyaMajmudar approved these changes
LGTM, thank you for the PR @Ritesh2351235 🚀

2024-12-13 08:27 UTC, benjagm approved these changes
LGTM

2024-12-13 08:28 UTC, merged