Improvements: Typos and grammatical errors in README.md
json-schema-org/website pull request #1081
Opened 2024-10-28 11:11 UTC by IyaadDev

**What kind of change does this PR introduce?**
- Fixed some typos, grammatical errors and added extra info in places for extra clarity

**Issue Number:**

-  Closes #1080

**If relevant, did you update the documentation?**
- Minor updates to README.md

**Summary**
- Quick fix for some grammatical errors, typos and improvements on some information

<p>*Feel free to check if there's anything I've missed out on*</p>

2024-10-28 11:15 UTC, IyaadDev commented
Ready to merge 👍
This pr just goes through the README.md though
There are plenty more of these grammatical issues around the documentation, will look over some of them and post an issue and pr on those too

2024-10-28 11:16 UTC, DhairyaMajmudar commented
Wow! Pretty quick, Thanks for the PR @IyaadDev... You can use this PR for pushing other changes too.

2024-10-28 11:18 UTC, DhairyaMajmudar commented on README.md
> +This repository contains the source code of JSON Schema NextJS app:
I think website would be an appropriate word here.

```suggestion
This repository contains the source code of JSON Schema website:
```

2024-10-28 12:51 UTC, IyaadDev commented
Later throughout the course of this week hopefully I'll be able to review the rest of the docs to suggest changes,
thanks @DhairyaMajmudar

2024-11-08 06:00 UTC, benjagm requested changes
Thanks for your contribution. I left just 1 single comment.

Good changes!

2024-11-08 06:00 UTC, benjagm commented on README.md
> +- JSON Schema Implementations
"Add a new JSON Schema Implementation" makes sense here. Please keep it.

2024-11-08 08:39 UTC, gregsdennis commented on README.md
> +Please refer to [INSTALLATION.md](./INSTALLATION.md) for instructions on how to set up the project on your machine.
```suggestion
Please refer to [INSTALLATION.md](./INSTALLATION.md) for instructions on how to set up the project for local development.
```

2024-11-11 12:43 UTC, IyaadDev commented on README.md
>  </a>
I think this should work?
```md
[![Contributors](https://contrib.rocks/image?repo=json-schema-org/website)](https://github.com/json-schema-org/website/graphs/contributors)
```

Preview:
[![Contributors](https://contrib.rocks/image?repo=json-schema-org/website)](https://github.com/json-schema-org/website/graphs/contributors)

2024-11-11 17:24 UTC, gregsdennis commented on README.md
> -    <a href="https://json-schema.org/slack" target="blank" style="margin-right: 5px;"><img align="center" src="https://img.icons8.com/color/48/null/slack-new.png" alt="JSON Schema Slack" height="30"
These each have height specified, which can't be put into markdown.

2024-11-23 09:15 UTC, benjagm requested changes
Just left a small comment.

2024-11-23 09:15 UTC, benjagm commented on README.md
> +- JSON Schema Implementations
Please keep "Add a new JSON Schema Implementation"

2024-12-09 15:20 UTC, IyaadArshad commented
I'll open a separate pull request for the rest of the changes,
that's about it for changes to the README.md

2024-12-09 17:01 UTC, IyaadArshad commented
#1080

2024-12-13 08:32 UTC, benjagm approved these changes

2024-12-13 08:33 UTC, benjagm commented
Great work!! Thanks!!

2024-12-13 08:33 UTC, merged