Fix: Sidebar position sticky
json-schema-org/website pull request #1086
Opened 2024-10-30 09:31 UTC by techmannih

**What kind of change does this PR introduce?**
This PR introduces a sticky sidebar position, allowing the sidebar to remain fixed in view while the user scrolls down the page. 

**Issue Number:**
Issue #774 
 Closes #774 

**Screenshots/videos:**

https://github.com/user-attachments/assets/9f203402-d5ae-4666-8f41-53beb27f34cf

2024-10-31 14:44 UTC, DhairyaMajmudar commented
@techmannih the sidebar should be sticky to such high extend.
 
![image](https://github.com/user-attachments/assets/754e623e-6dd8-422a-a849-23e7a15d405b)

2024-11-10 06:45 UTC, DhairyaMajmudar commented
@techmannih I was worried about the less bottom margin for the sidebar cause of which it was getting patched up with need help section you can check the video below 

 
[Screencast from 2024-11-10 12-07-28.webm](https://github.com/user-attachments/assets/c47f7e7d-fe85-4827-9648-db0b2bd74710)


The expected behavior should be like this : ) 

[Screencast from 2024-11-10 12-10-15.webm](https://github.com/user-attachments/assets/e3ee8dc6-3d1d-4e33-b4f5-b80afdab5df1)

2024-11-10 06:45 UTC, DhairyaMajmudar commented on components/Sidebar.tsx
> +          <div className='hidden lg:block mt-24 sticky top-24 h-[calc(100vh-6rem)] overflow-hidden'>
```suggestion
          <div className='hidden lg:block mt-24 mb-72 sticky top-24 h-[calc(100vh-6rem)] overflow-hidden'>
```

2024-11-10 06:46 UTC, DhairyaMajmudar commented on components/Sidebar.tsx
> +          <div className='hidden lg:block mt-24 sticky top-24 h-[calc(100vh-6rem)] overflow-hidden'>
By committing this suggestion you'll be good to go 👍🏻

2024-12-31 13:11 UTC, DhairyaMajmudar requested changes
@techmannih PR is working correct in local, but in hosted preview it's not showing expected behaviour. You need to merge the latest changes form main to your branch to fix this problem.

2025-01-01 05:37 UTC, DhairyaMajmudar approved these changes
LGTM 💯

2025-01-02 03:32 UTC, BHAVISHYA2005 commented
Good work @techmannih

2025-01-07 08:35 UTC, benjagm requested changes
The add component below the sidebar appears now cut missing almost 50% of the content. Can you please check.

2025-01-10 13:36 UTC, benjagm requested changes
There are still problems with this version when scrolling the sidebar with short pages. Please see the video how the sidebar appears confusingly cut and requires the user to scroll down on it. Expectation is to show all the content of the sidebar without having to scroll it.

See the recording demoing the issue here: https://drive.google.com/file/d/1vj5eCS2oym1Kope9bP8oqSwS6AeXFunI/view?usp=sharing

2025-01-18 11:54 UTC, benjagm approved these changes
LGTM

2025-01-18 11:54 UTC, merged