fix: Update CONTRIBUTING-docs.md with instructions for adding metadata to markdown files
json-schema-org/website pull request #1101
Opened 2024-11-09 16:23 UTC by techmannih

**Issue Number:**
-  Closes #1097 

This PR updates the CONTRIBUTING-docs.md file to include instructions on adding metadata (YAML front matter) to new markdown files.
Added guidelines for including metadata fields like title, section, date, author, and tags.

2024-11-14 10:35 UTC, kwennB requested changes
Good work, and thank you for your quick response to this issue.

2024-11-14 10:35 UTC, kwennB commented on CONTRIBUTING-docs.md
> +When contributing to the documentation, it's important to include metadata in every newly created markdown file. This metadata helps organize content and ensure consistency across all pages in the do
The metadata is essential for successfully building the markdown file. Please include it in the description, as the file will not render locally without it.

2024-11-14 10:35 UTC, kwennB commented on CONTRIBUTING-docs.md
> +When contributing to the documentation, it's important to include metadata in every newly created markdown file. This metadata helps organize content and ensure consistency across all pages in the do
There is a whitespace error between the first and second sentences. "_documentation.when_".

2024-11-14 10:35 UTC, kwennB commented on CONTRIBUTING-docs.md
> +When contributing to the documentation, it's important to include metadata in every newly created markdown file. This metadata helps organize content and ensure consistency across all pages in the do
It may be best to remove "here is an example of metadata" since you also repeated that phrase in the Example sub-section.

2024-11-14 11:35 UTC, kwennB commented
Here is the style guide to also help. https://github.com/json-schema-org/website/blob/main/pages/md-style-guide.md

2024-11-14 12:05 UTC, valeriahhdez commented
@techmannih, thanks for your hard work on improving the contribution guide! Your changes have made it clearer and more user-friendly.

I do have a small issue regarding the level of detail in the steps. For straightforward tasks, providing too many steps might come across as condescending. To avoid this, we could simplify the instructions by providing a high-level overview and letting the reader fill in the details.

Let me know if you have any questions.

2024-11-15 07:54 UTC, valeriahhdez requested changes
Thank you for your work on this PR!

We don't add detailed step-by-step instructions for straightforward tasks, like adding metadata to a .md file. I suggest adding a general instruction and letting the reader fill in the details themselves.

2024-11-15 08:02 UTC, gregsdennis commented on CONTRIBUTING-docs.md
> +### Steps for Adding Metadata:
I disagree. I think it's nice to know the properties which are used by the rendering engine. To my knowledge they're not standardized, even if there is a common convention.

2024-11-20 13:31 UTC, valeriahhdez commented
Looking good @techmannih! 

I left two more comments, but after you addressed them, it will be better to merge

2024-11-20 13:53 UTC, valeriahhdez commented
> @valeriahhdez Which comments are still pending? I believe these have already been updated. Could you please revise them again

@techmannih I tagged you in the comments I left a few minutes ago

2024-11-29 10:29 UTC, valeriahhdez commented
@techmannih here are the screenshots of the feedback that is pending to be addressed 

![Screen Shot 2024-11-29 at 11 28 06](https://github.com/user-attachments/assets/21cc7e20-868c-445a-b13d-1c134f569003)
![Screen Shot 2024-11-29 at 11 28 34](https://github.com/user-attachments/assets/20fa014b-9267-4d8c-a881-2682dccb5e98)
![Screen Shot 2024-11-29 at 11 28 52](https://github.com/user-attachments/assets/d373728d-825d-4631-896e-0c021b2bbce3)

2024-12-02 11:40 UTC, valeriahhdez commented
LGTM

Good job @techmannih

2024-12-02 11:40 UTC, valeriahhdez approved these changes
LGTM, googd job @techmannih

2024-12-10 08:38 UTC, kwennB approved these changes
LGTM 🚀🚀

2024-12-10 08:39 UTC, kwennB commented
@DhairyaMajmudar The docs team approves this PR.

2024-12-13 07:07 UTC, benjagm approved these changes
LGTM

2024-12-13 07:07 UTC, merged