Link-Redirect-fix-DocsHelp-Component
json-schema-org/website pull request #1117
Opened 2024-11-17 07:13 UTC by Yashwanth1906

What kind of change does this PR introduce?
           Change to correct wrong redirecting URLs
Issue Number:
closes: https://github.com/json-schema-org/website/issues/1038

Screenshots/videos:

If relevant, did you update the documentation?

Summary

This pull request addresses an issue related to incorrect URL redirection in the JSON Schema website. Users were being redirected to incorrect or unintended pages when clicking on certain links.

Changes Made:
Corrected Redirecting URLs: Updated the wrong redirecting URLs in various components to ensure they point to the correct destinations. This change enhances navigation and provides users with access to the intended content.

Refactored JSX Components: Adjusted the formatting of JSX components to comply with the project's style guide. Specifically, I ensured that there were proper spaces before closing brackets in the JSX tags, addressing the errors raised by the reviewers.

Code Consistency: Ensured consistency in the codebase by adhering to Prettier and ESLint rules, which included correcting formatting issues to enhance code readability and maintainability.

These changes improve user experience by ensuring that links function correctly, reducing frustration caused by misdirected navigation.

Does this PR introduce a breaking change?

No

2024-11-17 07:19 UTC, Yashwanth1906 commented
@DarhkVoyd  This is the new pull request for this closed pull request #1046 because of some git pull rebase issues. I have written all the tests and changed all the corrections that you said in that #1046 closed pull request. Sry for closing that pull request.

2024-11-17 08:13 UTC, aialok reviewed
LGTM. Testing part ✅️

2024-11-19 16:35 UTC, Yashwanth1906 commented
@aialok  Is everything fine with the pr ? Is there any one want to review it?

2024-11-26 13:39 UTC, DarhkVoyd requested changes
Hey, thanks for working on this. This is almost done, just a few suggestions:
1. We can get rid of the `console.log`
2. Since the prop name has been updated to `fileRenderType`, let's update the passed argument variable name to reflect the change. As I have suggested at one of the instances.

2024-11-26 13:39 UTC, DarhkVoyd commented on pages/[slug].page.tsx
> +  const markdownFile = '_md';
```suggestion
  const fileRenderType = '_md';
```

2024-11-26 18:05 UTC, Yashwanth1906 commented
@DarhkVoyd  Done with all the changes suggested.

2024-12-15 14:50 UTC, DarhkVoyd commented
@Yashwanth1906 Hey, could you please resolve the conflicts in the PR? I'll review this PR soon.

2024-12-16 11:05 UTC, Yashwanth1906 commented
@DarhkVoyd ok Ill finsih this as soon as possible

2024-12-16 11:25 UTC, DarhkVoyd commented
Hey @Yashwanth1906 You don't have to close existing PR and create a new PR for each change/review, you can continue working on the same branch and PR, we'll squash merge it.

2024-12-17 04:42 UTC, Yashwanth1906 commented
@DarhkVoyd ok

2024-12-17 12:53 UTC, Yashwanth1906 commented
@DarhkVoyd Hi, I have tried pulling and merging the files and it resulted in mess and i added some packages and now im superconfused how to resolve this thing. Could I make another clean PR with all the tests and changes that you told in this PR.

2024-12-18 09:26 UTC, closed without merging