fix: Implement a TOC component
json-schema-org/website pull request #1127
Opened 2024-11-19 11:51 UTC by techmannih

**What kind of change does this PR introduce?**
 This PR introduces a new Table of Contents (TOC) component to improve the navigation within long documentation pages. It parses the markdown content and dynamically generates a list of links to the headers, making it easier for users to navigate the page

**Issue Number:**
-  Closes #1109

2024-12-08 12:40 UTC, valeriahhdez commented
Hi @techmannih, 

I'm not sure I understand what you mean by "there's no heading for these sections in the docs". Can you please expand on that?

2024-12-12 09:30 UTC, valeriahhdez commented
Summary of our Slack discussion:

- The endpoints' content lacks headings and therefore the TOC is empty when generated. 
- The documentation team will edit this documentation and reorganize its content by headings. This will improve the readers' experience by making it easier to scan and find information. 
- Editing the documentation is outside the scope of this PR, so we will create a separate issue for the task.

2024-12-12 10:46 UTC, valeriahhdez commented
Hi @DhairyaMajmudar, can you please help us review this PR?

2024-12-13 01:18 UTC, DhairyaMajmudar commented
@techmannih pls. fix the failing ci

2024-12-21 15:43 UTC, benjagm requested changes
Hi @techmannih . At first look,  it seems that you are repeating the same structure again and again in all pages, all with a lot of repeated code an static code. This is a typical scenario where is better to think about creating a standard component to make all this process much easier.

Check for the Layout.tsx component used to build the layouts. Maybe you can do this by default there.

What do you think?

2024-12-27 09:39 UTC, benjagm commented
> I am following the previous TOC that was built for the blog pages. Please check this one.

My expectation with this PR is to avoid having to add the TOC to every single page instead of having it generated automatically at the layout level the same way we have the sidebar automatically generated.

2024-12-27 09:40 UTC, benjagm requested changes
My expectation with this PR is to avoid having to add the TOC to every single page. Instead, it would be great having it generated automatically at the layout level the same way we have the sidebar automatically generated.

2025-01-18 11:55 UTC, benjagm commented
Hi @techmannih Are you still working on this?

2025-01-25 09:45 UTC, benjagm commented
> what's your opinion?

@DarhkVoyd can you take a look and check if you can come up with with alternative ideas to make this fully dynamic?

2025-01-25 17:34 UTC, DarhkVoyd commented
> > what's your opinion?
> 
> @DarhkVoyd can you take a look and check if you can come up with alternative ideas to make this fully dynamic?

Sure, I'll have a look and report back to you.

2025-01-28 16:36 UTC, DarhkVoyd commented
Is this a high priority issue? I'm planning to work on this on the weekend.

2025-01-28 16:37 UTC, benjagm commented
> Is this a high priority issue? 

Of course not. Take your time DV.

2025-03-05 21:59 UTC, benjagm commented
Closed as there has been no activity in the last month.

2025-03-05 21:59 UTC, closed without merging