Fix problems with table rendering
json-schema-org/website pull request #1145
Opened 2024-12-01 17:36 UTC by benjagm

**Summary**

It has been notified in [slack](https://json-schema.slack.com/archives/C8C4UBXDF/p1732991084724689) an issue with the markdown tables rendering. This PR fixes it.

2024-12-01 22:55 UTC, karenetheridge commented
The preview (https://json-schema-org-benjagm-fix-3r57.website-2v2.pages.dev/) seems to show a different page.

2024-12-02 13:26 UTC, DarhkVoyd reviewed
<details>
<summary>Details</summary>

<details>
<summary>Details</summary>

<details>
<summary>Details</summary>

Thanks for this. Could we also address the link rendering bug and some inconsistencies in back-ticks markdown highlighting?

![Screenshot 2024-12-02 at 6 54 36 PM](https://github.com/user-attachments/assets/6d35579a-6c94-488c-b97d-fc85b0d89ab2)

![Screenshot 2024-12-02 at 6 55 06 PM](https://github.com/user-attachments/assets/14f560fc-2c87-4c0f-a78f-12b0d45904b2)

</details>

</details>

</details>

2024-12-05 17:14 UTC, karenetheridge approved these changes
a few comments follow...

2024-12-05 17:20 UTC, karenetheridge requested changes
I clicked around a bit more...

This file looks a bit off: https://json-schema-org-benjagm-fix-3r57.website-2v2.pages.dev/draft/2020-12/release-notes (at "$dynamicRef and $dynamicAnchor").

Also selecting the headings results in the underlying html ending up in the copy buffer, which is really weird! but I don't know if that's new, or an artifact of how the preview is generated.

And the links in the markdown tables at https://json-schema-org-benjagm-fix-3r57.website-2v2.pages.dev/draft/2019-09/release-notes are not rendering still.

2024-12-22 16:59 UTC, benjagm commented
@DarhkVoyd I spent some hours today trying to fix this without success. I know that the problem is that we need the markdown to be processed recursively for cases like these:
````
      <td>
        ```json
        {
          "items": [
            { "$ref": "#/$defs/foo" },
            { "$ref": "#/$defs/bar" }
          ]
        }
        ```
      </td>
````

or 

````
| keyword | change | notes
| ---- | ---- | ----
[`dependentSchemas` (split from `dependencies`)](../../draft/2019-09/json-schema-core.html#rfc.section.9.2.2.4) | **split** | This is the schema form of `dependencies`; note that the standard meta-schema still reserves `dependencies` for backwards compatibility
[`unevaluatedItems`](../../draft/2019-09/json-schema-core.html#rfc.section.9.3.1.3) | **new** | Similar to `additionalItems`, but can "see" into subschemas and across references
[`unevaluatedProperties`](../../draft/2019-09/json-schema-core.html#rfc.section.9.3.2.4) | **new** | Similar to `additionalProperties`, but can "see" into subschemas and across references
````

We are rendering the top-level element but not what it is inside.

Do you have time to give it a try?

2024-12-23 08:33 UTC, DarhkVoyd commented
In my opinion, we have correctly configured the Markdown to JSX transpiler. However, the issue lies within the package. The simplest solution here would be to write the Markdown as:
```markdown
| Keyword                                                                                                                         | Change    | Notes                                                                                                                                         |
| ------------------------------------------------------------------------------------------------------------------------------- | --------- | --------------------------------------------------------------------------------------------------------------------------------------------- |
| <a href="../../draft/2019-09/json-schema-validation.html#rfc.section.6.5.4">`dependentRequired` (split from `dependencies`)</a> | **split** | This is the string array form of `dependencies`; note that the standard meta-schema still reserves `dependencies` for backwards compatibility |
| <a href="../../draft/2019-09/json-schema-validation.html#rfc.section.6.4.4">`maxContains` and `minContains`</a>                 | **new**   | Assertion for controlling how many times a subschema must be matched within an array                                                          |

```

2024-12-23 08:43 UTC, benjagm commented
> In my opinion, we have correctly configured the Markdown to JSX transpiler. However, the issue lies within the package. The simplest solution here would be to write the Markdown as:
> 
> ```
> | Keyword                                                                                                                         | Change    | Notes                                                                                                                                         |
> | ------------------------------------------------------------------------------------------------------------------------------- | --------- | --------------------------------------------------------------------------------------------------------------------------------------------- |
> | <a href="../../draft/2019-09/json-schema-validation.html#rfc.section.6.5.4">`dependentRequired` (split from `dependencies`)</a> | **split** | This is the string array form of `dependencies`; note that the standard meta-schema still reserves `dependencies` for backwards compatibility |
> | <a href="../../draft/2019-09/json-schema-validation.html#rfc.section.6.4.4">`maxContains` and `minContains`</a>                 | **new**   | Assertion for controlling how many times a subschema must be matched within an array                                                          |
> ```

Thanks for analyzing it DV. While this seems something valid when talking about link inside tables,  there are scenarios where we have other stuff like code snippets using the default code block and this is not working as well:

https://json-schema.org/draft/2020-12/release-notes#dollardynamicref-and-dollardynamicanchor

I think what we have is just rendering once, and is not doing the job for other formats inside certain blocks. If we manage to recursively apply formatting we should be able to fix it. I tried this yesterday and managed to make it work for links and other formats, but not code blocks with code snippets.

2024-12-23 08:54 UTC, DarhkVoyd commented
@benjagm Understood. I'll fix this.

2024-12-23 17:19 UTC, DarhkVoyd commented
@benjagm  I reviewed the library’s source code and the library does parse markdown recursively but the parse logic for table cell content is incorrect. Instead of treating cell content as a single string, it splits it into fragments and loses context, leading to incorrect plain text rendering. 

Regarding the code block, it is unrelated as table cells often fail to render properly due to unnecessary line breaks, the fix is simply to remove the unnecessary empty lines between `<td>` and ` ```jsonc`



For the original table parsing problem, I’ve submitted a detailed issue and suggested a fix for the parsing logic. You can find it here: [quantizor/markdown-to-jsx#644](https://github.com/quantizor/markdown-to-jsx/issues/644)

2025-01-07 06:21 UTC, DarhkVoyd commented
The submitted issue to fix the parsing logic has been attended and a fix has been merged. Should be soon available in a release.

2025-01-07 07:57 UTC, benjagm commented
> The submitted issue to fix the parsing logic has been attended and a fix has been merged. Should be soon available in a release.

Thanks for the update DV!

2025-01-07 12:04 UTC, DarhkVoyd commented
The release with fix is now available as v7.7.3.

2025-01-07 12:36 UTC, benjagm commented
@DarhkVoyd, Amazing job finding the problem, filing the issue in the markdown-to-jsx dependency, and tracking the problem!! Awesome job.

I just updated the dependency, and the issue with most of the styles has been solved and the only one persisting is the one with the code editor to show code snippets inside cells:

https://json-schema-org-benjagm-fix-3r57.website-2v2.pages.dev/draft/2020-12/release-notes#dollardynamicref-and-dollardynamicanchor

Any idea about what is causing this?

2025-01-07 13:28 UTC, DarhkVoyd commented
Thanks for the kind words! . Regarding the code editor issue, table cells often fail to render properly due to unnecessary line breaks, the fix is simply to remove the unnecessary empty lines between <code>\<td></code> and  <code>```jsonc</code> just like all other instances.
<div style="display: flex; flex-direction: row; justify-content: space-between; align-items: center;">
  <div>
    <p>Before:</p>
    <img width="400" alt="Before" src="https://github.com/user-attachments/assets/1d4026c8-be8a-468e-b8f7-482599cfb784" />
  </div>
  <div>
    <p>After:</p>
    <img width="400" alt="After" src="https://github.com/user-attachments/assets/ece47772-5bef-4980-990d-eefec08b01f0" />
  </div>
</div>

2025-01-07 16:07 UTC, benjagm commented
Thanks DV. Now everything seems to work. I just re-requested reviews by everyone.

2025-01-08 12:40 UTC, DarhkVoyd reviewed
https://json-schema-org-benjagm-fix-3r57.website-2v2.pages.dev/draft/2020-12/release-notes#dollardynamicref-and-dollardynamicanchor still seems to be broken on the build preview but works as desired on the localhost, what am I missing? All else looks good to me.

2025-01-08 12:42 UTC, DarhkVoyd commented
Does this PR predate the PR build preview cache issue fix? Does its preview build still use the outdated cache workflow?

2025-01-09 13:10 UTC, DarhkVoyd approved these changes
The preview works fine now! Looks good to me, ready to merge!

2025-01-10 13:10 UTC, benjagm commented
> I clicked around a bit more...
> 
> This file looks a bit off: https://json-schema-org-benjagm-fix-3r57.website-2v2.pages.dev/draft/2020-12/release-notes (at "$dynamicRef and $dynamicAnchor").
> 
> Also selecting the headings results in the underlying html ending up in the copy buffer, which is really weird! but I don't know if that's new, or an artifact of how the preview is generated.
> 
> And the links in the markdown tables at https://json-schema-org-benjagm-fix-3r57.website-2v2.pages.dev/draft/2019-09/release-notes are not rendering still.

Now everything is fixed.

2025-01-18 11:44 UTC, merged