add introductory guide to JSON Schema
json-schema-org/website pull request #1148
Opened 2024-12-02 17:03 UTC by techmannih

**Issue Number:**
-  Closes #1129

2024-12-19 18:02 UTC, valeriahhdez commented
> @valeriahhdez please review this PR

Hi @techmannih, 

Yes, I'll review it.

2024-12-21 13:21 UTC, DhairyaMajmudar commented
@techmannih it seems like ci checks are failing pls. fix them

2024-12-23 10:49 UTC, valeriahhdez requested changes
Hi @techmannih, 

This is a good starting point!

I left some line comments but here are my high-level observations:

- It seems to me the document lacks clear goals where the reader starts at point A and finishes at point B. 
- Because of this, the document jumps from very basic (empty schema) to complex (nested objects) without a clear progression. 
- It needs to be improved to build knowledge incrementally. 
- In some parts of the text, ideas don't flow naturally, for example when you talk about `$ref` keyword. 
- It needs to be revised for style. I invite you to read and consult from time to time our [style guide](https://github.com/json-schema-org/website/blob/main/pages/md-style-guide.md). 

But overally, I think this is a good first draft. Let me know if you have any questions about these comments. 

I look forward to the next iteration of improvements!

2024-12-23 10:49 UTC, valeriahhdez commented on pages/understanding-json-schema/introduction.md
> +address is defined as an object with its own properties.
Use code formatting for `address`

2024-12-23 10:49 UTC, valeriahhdez commented on pages/understanding-json-schema/introduction.md
> +The required keyword is used to ensure certain fields are present.
Please review the text for code-formatting of keywords

2024-12-27 09:35 UTC, benjagm commented
How this new page differs from https://json-schema.org/overview/what-is-jsonschema

Why we need a new one?

2025-01-06 16:50 UTC, valeriahhdez commented
> How this new page differs from https://json-schema.org/overview/what-is-jsonschema
> 
> Why we need a new one?

To answer your questions @benjagm, I am pasting what I wrote in issue #1129. But let me know if anything needs further clarification. 
The following documents: 
- [What is a schema?](https://json-schema.org/understanding-json-schema/about)
- [The basics](https://json-schema.org/understanding-json-schema/basics)

are formatted as book chapters which means that they present information in a sequential manner and each chapter builds upon the previous one. This means the reader needs to complete more than one chapter to complete a task or learning lesson. We want each one of our documentation to be self-contained so that readers can quickly find the information they are looking for. 

An introductory guide to JSON Schema that is self-contained should comply with the following requirements to replace the book chapters mentioned above:

- clear learning goals for the reader
- a start and end points
- link to other learning resources
- be clear, concise, and accurate

However, I forgot to mention in the issue that we can use one of the existing files for this self-contained guide; we don't need to create a new Markdown document.

2025-01-12 12:34 UTC, valeriahhdez commented
Hi @benjagm, 

Can we continue working on this PR?

2025-01-25 10:01 UTC, benjagm commented
Hi Team, I am not fully aligned with the goal of this issue. We already have a [What is JSON Schema](https://json-schema.org/overview/what-is-jsonschema) page in the overview section and a What is JSON Schema in [Reference](https://json-schema.org/understanding-json-schema/about). 

This PR is now adding a new page with the same information and also generating duplicities in the Reference section: 
<img width="1409" alt="Screenshot 2025-01-25 at 11 00 49" src="https://github.com/user-attachments/assets/9aa8fe91-9c9a-4916-becd-9d4cc752cdd4" />
<img width="1496" alt="Screenshot 2025-01-25 at 11 00 41" src="https://github.com/user-attachments/assets/44bb6bfd-0fbd-4578-aa66-a6aef2a8e948" />

Honestly, I think https://json-schema.org/understanding-json-schema/about is enough.

2025-01-27 14:55 UTC, benjagm commented
Hi @valeriahhdez and @techmannih . First of all sorry if my feedback was too direct here. It wasn't my intention so first of all let me apologize. We are so grateful for all the contributions... and sorry I'm my feedback was not transmitting that same spirit.

Looking into the root cause here I think there are 2 key elements:
- The issue #1129 is stating that the expected outcome of this feature is creating a guide, however I think that is not correct. The resulting document is going to live into the Reference section, therefore we are expecting a Reference Document which goals and structure is totally different.  I added this as comment to the issue but I think this is the first reason of the difference in terms of expectation.
 - The second element, is creating another guide called "What is JSON Shema" we are creating a duplicity with "What is JSON schema" in the overview section, a page with almost same title than "What is a Schema". In my opinion, what we would need here is an "Introduction to the JSON Schema Reference" as a reference doc.
 
 I hope this makes sense. And again, sorry for rushing my feedback in the previous review.

2025-02-02 09:54 UTC, valeriahhdez commented
I agree this document shouldn't live in the reference documentation, but we could move it to the Guides content bucket that I'm proposing for the New Architecture Infrastructure PR. 

I don't think the reference documentation needs an introductory document. The overview pages I am proposing to add in the new architecture infrastructure  PR already describe what the reference documentation contains, giving the readers clear expectations for this content bucket. 

Whatever we end up doing, I do think something has to be done about these documents

- [What is a schema?](https://json-schema.org/understanding-json-schema/about)
- [The basics](https://json-schema.org/understanding-json-schema/basics)

because they are formatted as book chapters instead of self-contained documents.

2025-03-16 17:40 UTC, benjagm commented
After long consideration, I think the current status of the site doesn't require this change. Thanks a lot for your resilience and commitment. Next time we'll do a better job during the triage.

2025-03-16 17:40 UTC, closed without merging