Add Quick Guide for Writing Tests to Contributing Documentation
json-schema-org/website pull request #1151
Opened 2024-12-06 14:02 UTC by yadavshubham01

This pull request adds a new section to the contributing-docs.md file, providing a quick guide for writing effective tests. It includes best practices for test structure, naming conventions, and details on creating tests with Cypress, both for components and end-to-end (E2E) scenarios. Additionally, it provides resources for further reading on test writing.

How This Solves the Issue: The enhancement improves the contributing.md documentation by adding clear, concise instructions for contributors on how to write and structure tests. This ensures that new contributors have a reliable reference for implementing tests alongside their contributions, promoting consistency and quality in test coverage. The addition of this guide helps maintain robust and maintainable tests across the project.

Issue Number:
-  Closes #1147

2024-12-06 14:04 UTC, yadavshubham01 commented
hey @kwennB please review this PR

2024-12-06 15:09 UTC, kurtmckee commented
@yadavshubham01 I noticed that you repeatedly edited your "please review this PR" request to @-mention different people, including me in one edit.

1. I've never contributed to this repo to the best of my knowledge. Your manual effort to ping me was unnecessary.
2. I see from your GitHub activity that you consistently, and immediately, ping people on every PR you open on GitHub.

   _Please stop doing this._ As demonstrated here, it's error prone (you might ping people who have nothing to do with the repo), and is unnecessary because repo owners typically receive notifications about PRs opened.

Thanks for your work to contribute to open source! I wish you well.

2024-12-06 16:05 UTC, yadavshubham01 commented
Apologies for the inconvenience, I will be more careful next time

2024-12-07 01:01 UTC, gregsdennis requested changes
Please hold on this while we discuss in the issue. cc: @valeriahhdez

2024-12-10 09:16 UTC, valeriahhdez commented
Hello @yadavshubham01, 

Thank you for your work on this PR. The triage team reviewed issue #1147 and found that the project's needs were not clearly described and incorrectly pointed to the CONTRIBUTING-docs.md file as the place to document test guidelines. 

Here are the key points from the triage team's review: 
- Issue #1147 addresses the lack of guidelines on writing tests for the website's components. 
- the guidelines should be documented in the CONTRIBUTING.md guide, not in the CONTRIBUTING-docs.md. 

If you still want to work on issue #1147 we kindly ask you to commit your changes to the CONTRIBUTING.md guide. We apologize for any inconvenience caused. The maintainer's team had not yet triaged the issue when you opened the PR.

To prevent similar situations in the future, we are adding a new rule to our CONTRIBUTING.md guide: contributors should wait until they are assigned to an issue before starting work on the changes.

Thank you for your understanding and have a nice day.

2024-12-10 10:03 UTC, yadavshubham01 commented
hey @valeriahhdez i will make change in CONTRIBUTING.md

2024-12-19 15:46 UTC, yadavshubham01 commented
hey @valeriahhdez  please review i fix that changes in CONTRIBUTING.md

2024-12-27 09:47 UTC, benjagm requested changes
I dont see the benefit of adding generic information about testing, lets please avoid that.

We already have the contributing to testing section with some basic guidelines about how to add tests to your code but it seems that is not enough. My expectation is to add some more tech details for everyone to understand how to implement the tests for their code when contributing to the project.

2025-01-07 08:43 UTC, benjagm requested changes
Some comments from my side:
* I'll suggest we keep this as simple as possible.
* I think we should focus on very specific instructions to effectively write tests for the website repo.
* Just adding code snippets to point 1 should be enough IMHO.

2025-01-18 11:58 UTC, benjagm commented
Hi @yadavshubham01 . Did you have the chance to review my comments?

2025-01-18 12:49 UTC, yadavshubham01 commented
@benjagm i fix this and make this simplify and focus the instructions.

2025-03-05 23:16 UTC, benjagm commented
Thanks a lot for the huge effort you have putted on this but I still don't see the fitting in the contributing guide. The content is still generic information about the writing test. We expect contributors to have that basic previous knowledge and acquire without our guidance. We can explain how to build a test for our project but in that case probably this will go inside the installation.md file where there is a deep explanation no how to setup the test environment.

Again sorry for having for iterating on this to finally not merging it... i just needed some time to be sure about the final decision.

2025-03-05 23:16 UTC, closed without merging