enhancement: new 404 page
json-schema-org/website pull request #1152
Opened 2024-12-07 21:37 UTC by r3yc0n1c

**What kind of change does this PR introduce?**
enhancement

**Issue Number:**

-  Closes #1082 

**Screenshots/videos:**

### Desktop View:
![image](https://github.com/user-attachments/assets/d5f0f3d2-418a-4ebf-b213-053db8c5aa07)
![image](https://github.com/user-attachments/assets/efd137d0-2039-4f20-b2fb-31a9963bd2d9)

---
### Mobile View:
![image](https://github.com/user-attachments/assets/bb026f18-0795-4549-a830-8166a15767bd)
![image](https://github.com/user-attachments/assets/a94f78d7-18d7-4d30-82b5-fb59f4c8890d)

**Summary**

- Designed and implemented the 404 page taking inspirations from [this mockup](https://github.com/json-schema-org/website/issues/1082#issuecomment-2453317342).

**Does this PR introduce a breaking change?**

No

2024-12-09 15:03 UTC, r3yc0n1c commented
I think we can keep the navbar with the logo on the top left as it is.

2024-12-27 09:32 UTC, benjagm commented
Any update on this one?

2024-12-27 11:09 UTC, r3yc0n1c commented
waiting for the logo position confirmation

2025-01-18 11:59 UTC, benjagm commented
Just add the logo centered un the upper part of the screen with a link to the landing page.

2025-01-18 13:05 UTC, r3yc0n1c commented
> Just add the logo centered un the upper part of the screen with a link to the landing page.

sure, working on it

2025-01-27 19:26 UTC, DhairyaMajmudar commented
@r3yc0n1c it's been a month, any updated on this PR? Do you need any help?

2025-01-27 19:27 UTC, r3yc0n1c commented
sorry for the delay, I'll wrap this up by tomorrow morning

2025-01-28 15:12 UTC, r3yc0n1c commented
Mobile:
| Mode | Desktop | Mobile |
| :--------: | :-------: | :--------: |
| Light | ![image](https://github.com/user-attachments/assets/a90a351d-8678-41d1-9883-9a0a511cb8e0) | ![image](https://github.com/user-attachments/assets/01705fdd-d6e3-4e3a-b6a5-89b1fc6c9064)  |
| Dark | ![image](https://github.com/user-attachments/assets/ab4459a7-08e8-4eef-b052-fefc38037c1e) | ![image](https://github.com/user-attachments/assets/52d81c73-4a35-4217-9a1a-dfd5584a33de) |

2025-03-06 03:33 UTC, DhairyaMajmudar requested changes
Awesome PR @r3yc0n1c we are very close, just some minor suggestions then we're Good to Go 🚀

2025-03-06 03:33 UTC, DhairyaMajmudar commented on pages/404.page.tsx
> +        className='flex items-center justify-center rounded border-2 border-white dark:border-none hover:bg-blue-700 transition-all duration-300 ease-in-out text-white w-[194px] h-[40px] font-semibol
```suggestion
        className='flex items-center justify-center rounded border-2 border-white dark:border-none hover:bg-blue-700 transition-all duration-300 ease-in-out text-white w-[194px] h-10 font-semibold bg-primary dark:shadow-2xl'
```

2025-03-06 03:33 UTC, DhairyaMajmudar commented on pages/404.page.tsx
> +      {/* mobile view */}
Remove comments

2025-03-06 03:33 UTC, DhairyaMajmudar commented on pages/404.page.tsx
> +  const [imageSrc, setImageSrc] = useState('/img/logos/logo-blue.svg'); // Default to match the server-side render
Remove comments

2025-03-06 10:04 UTC, r3yc0n1c commented on pages/404.page.tsx
> +        className='flex items-center justify-center rounded border-2 border-white dark:border-none hover:bg-blue-700 transition-all duration-300 ease-in-out text-white w-[194px] h-[40px] font-semibol
done

2025-03-06 10:04 UTC, r3yc0n1c commented on pages/404.page.tsx
> +      {/* mobile view */}
done

2025-03-06 10:04 UTC, r3yc0n1c commented on pages/404.page.tsx
> +  const [imageSrc, setImageSrc] = useState('/img/logos/logo-blue.svg'); // Default to match the server-side render
done

2025-03-09 05:10 UTC, DhairyaMajmudar approved these changes
LGTM 🚀

2025-03-16 17:18 UTC, benjagm approved these changes
LGMT

2025-03-16 17:18 UTC, merged