New information architecture
json-schema-org/website pull request #1194
Opened 2024-12-21 15:41 UTC by valeriahhdez

**What kind of change does this PR introduce?**
This PR changes the information architecture of the documentation with the following changes:

- Aligns content buckets to the diataxis framework to documentation. 
- Creates a new content bucket for Guides (to be populated)
- Restructures the navigation of the Reference content bucket by eliminating deep nesting. 
- Edits titles for consistency and clarity. 
- Reallocates documents to create a coherent organization. 
- Adds context and expectations to content buckets and Reference sections that contain nested documents with Overview pages. 

**Issue Number:

-  Closes #790  
-  Related to #158  
-  Others? 

**Screenshots/videos:**

**If relevant, did you update the documentation?**
Yes, I made changes to several documents within the reference content bucket. 

**Summary**

This PR addresses the needs of the [GSoD project](https://github.com/orgs/json-schema-org/discussions/687), more specifically, [milestone 5](https://github.com/json-schema-org/website/issues/158#release5) of the documentation strategy. 

The problem: we need to reorganize the information in a coherent way to onboard people new to JSON Schema and make it easier for readers to find what they’re looking for. 

The goals:
- To streamline developer workflows by revamping our documentation architecture with the diataxis approach. 

- To conduct a style overhaul for a more intuitive and cohesive developer experience.

You can see a slide deck summarizing this work [here](https://docs.google.com/presentation/d/1IalPeuexOy9NhKYx0_3qmghLdKOqW33P0ZxHEiAq2DQ/edit?usp=sharing). 

**Does this PR introduce a breaking change?** No

2024-12-25 12:53 UTC, DhairyaMajmudar requested changes
@valeriahhdez pls. resolve the failing lint workflow. For doing so you've to run the command `yarn run lint:fix`

2024-12-25 12:55 UTC, DhairyaMajmudar commented on pages/learn/guides/index.page.tsx
> +import Card from '~/components/Card';
Pls. remove this unused import

2025-01-12 12:33 UTC, valeriahhdez commented
Hi @benjagm, 

Can you please review this PR?

2025-01-26 22:51 UTC, benjagm requested changes
This is looking awesome!!

This is almost done, I just found some small comments I am providing below:

 - Rebase to the last changes to get the implementation of the prev / next buttons.
 - The PR is missing all the redirects implemented in "public/_redirects" from pages we are removing from the sidebar like:
 	- /understanding-json-schema
 - Introduction - Looks great
 - Getting Started - Looks great
 	- "JSON Schema common terms" I would say the title seems now confusing. I would suggest we leave JSON Schema Glossary for now.
 - Guides 
 	- I suggest we move here "For Implementers" currently in Reference.
 - Reference
 	- I think we could add some additional links in the Overview page at the bottom with some links and a message in case the users is looking for the very basic:
 		- What is JSON Schema
 		- What is a Schema
 		- The basics
 		- Creating your first Schema. 
 	And another link to Specification in case the user is looking for the Spec itself?
 	- I suggest we move to the bottom "Learn JSON Schema" as a complementary resource to the reference.
 	- The overview page cards is missing 2 subsections:
 		- Conditional schema validation
 		- Media: string-encoding non-JSON data
	-  I suggest we move here "For Implementers" into guides.


Great work. This is just small details.

2025-02-15 12:34 UTC, valeriahhdez commented
I am closing this PR to open a new one that contains the Prev/Next navigation and the changes requested in this review.

2025-02-15 12:34 UTC, closed without merging