docs: add note clarifying multipleOf implementation
json-schema-org/website pull request #1206
Opened 2024-12-23 14:58 UTC by inclinedadarsh

**What kind of change does this PR introduce?**

Documentation update

**Issue Number:**

-  Closes #1113 

**Screenshots/videos:**

![image](https://github.com/user-attachments/assets/edf30ec4-5fda-423b-8f63-ec739fe63c9b)

**Summary**

Add a note explaining the difference between float-point implementation of programming languages and json schema

**Does this PR introduce a breaking change?**

No, it does not.

**Other**

I believe this note can be clearer, better if I also provide an example, not sure about it though. Please let me know about it.

2024-12-30 20:56 UTC, jdesrosiers requested changes
Thanks for giving this a start. There are a few things that need a second draft.

> The JSON Specification allows an arbitrary implementation of the `multipleOf` keyword

The JSON _Schema_ Specification defines `multipleOf`, not the JSON Specification. There is nothing arbitrary about `multipleOf`. It has a precise definition and consistent behavior across implementations. I'm not sure what this statement is trying to communicate to the reader, but it's full of inaccuracies.

> and is not constrained by the floating-point behavior of most programming languages.

This part is correct.

> In contrast, most programming languages adhere to the IEEE754 standard for floating-point numbers, which can result in discrepancies between validation according to the JSON Specification and the behavior in programming languages.

This is correct, but not the way I would frame it. I would say that with JSON Schema you don't need to worry about the limitations of IEEE754 floating-point numbers like you do in most programming languages.

2024-12-31 18:28 UTC, inclinedadarsh commented
Thanks a lot for the review @jdesrosiers 

Thank you specifying exact changes needed, I'll be fixing these and would push the changes as soon as possible.

2025-01-06 20:19 UTC, jdesrosiers requested changes
This sounds better but there's still an inaccuracy.

2025-01-06 20:19 UTC, jdesrosiers commented on pages/understanding-json-schema/reference/numeric.md
> +<Infobox label="Note"> The JSON Schema Specification defines numerical precision independently of the IEEE 754 standard. This means developers do not need to worry about the typical limitations of fl
You still have this a little confused. The JSON specification defines numbers. The JSON Schema specification defines `multipleOf` using JSON numbers.

2025-01-23 12:10 UTC, inclinedadarsh commented on pages/understanding-json-schema/reference/numeric.md
> +<Infobox label="Note"> The JSON Schema Specification defines numerical precision independently of the IEEE 754 standard. This means developers do not need to worry about the typical limitations of fl
Hey, so sorry for this.
Can you redirect me to a page where I can read more about it, to clear my confusion?

2025-01-23 19:17 UTC, jdesrosiers commented on pages/understanding-json-schema/reference/numeric.md
> +<Infobox label="Note"> The JSON Schema Specification defines numerical precision independently of the IEEE 754 standard. This means developers do not need to worry about the typical limitations of fl
It's the [JSON specification](https://www.rfc-editor.org/rfc/rfc8259#section-6) that defines numbers, not the JSON Schema specification. That's the only thing that needs to change. The JSON Schema specification also [mentions](https://json-schema.org/draft/2020-12/draft-bhutton-json-schema-01#section-4.2.1) the JSON data model, but just as a reader convenience.

2025-01-23 19:37 UTC, jdesrosiers approved these changes

2025-02-01 12:22 UTC, merged