[Feat]-Add JSON Schema Editor tool
json-schema-org/website pull request #1210
Opened 2024-12-26 11:08 UTC by MadhavDhatrak

**What kind of change does this PR introduce?**
Feature: Added a new tool – JSON Schema Editor.

**Issue Number:**
-  Closes #1118 

**Screenshots/videos:**

https://github.com/user-attachments/assets/dbcf75b7-f24b-4cfc-9b50-9ef80d0100f6

**If relevant, did you update the documentation?**
Documentation not required as this is a  tool addition.

**Summary**
This PR introduces the JSON Schema Editor tool to the platform. It allows users to:

- Easily build JSON schemas using an intuitive UI.
- Convert JSON schemas into formats like SQL, GraphQL, and Protocol Buffers.
- Generate sample data conforming to the defined JSON schema.
- The addition enhances developer productivity by streamlining JSON schema creation and format conversions.

**Does this PR introduce a breaking change?**

No breaking changes introduced.

2024-12-26 15:19 UTC, DhairyaMajmudar approved these changes
Thanks for the PR @MadhavDhatrak, LGTM 👍🏻

2024-12-27 09:58 UTC, Relequestual requested changes
As far as I can tell, this only supports top level, and is very limited feature wise. I feel like we need to add something about this in the tooling listing notes.

2024-12-27 11:08 UTC, MadhavDhatrak commented
Hi @Relequestual ,

Thanks for the feedback! I've updated the PR to mention that the tool currently supports only top-level JSON schema creation.

I have also added the following tooling types to reflect the current functionality:
```'editor'```
```'util-format-conversion'```
```'util-schema-to-schema'```

Screenshot
![Screenshot 2024-12-27 163516](https://github.com/user-attachments/assets/58eba589-85b0-4b2a-af23-5918eb2183ff)

Please review my changes and let me know if any further adjustments are needed.

2024-12-31 17:05 UTC, robclarabase commented
> As far as I can tell, this only supports top level, and is very limited feature wise. I feel like we need to add something about this in the tooling listing notes.

Hi @Relequestual - I worked on this project and would like to make the improvements you mentioned here in a subsequent iteration (not that it should be a blocker to this PR). Just so I understand correctly, does "only supports top level" refer to the lack of support for nested properties with an "object" type? Also what features/functionality would it need for it not be considered limited? Thanks!

2025-01-02 05:46 UTC, closed without merging