feat: highlight fragement headings when clicked
json-schema-org/website pull request #304
Opened 2024-02-11 17:57 UTC by Min2who

**GitHub Issue:** #303 

**Summary**:

**Do you think resolving this issue might require an [Architectural Decision Record (ADR)](https://github.com/json-schema-org/community/blob/main/CONTRIBUTING.md#key-architectural-decisions)? (significant or noteworthy)**

No
[JUSTIFICATION]

2024-02-11 17:59 UTC, Min2who commented
**DONT MERGE THIS**

As would like to refractor some code and want to close #303  in this PR only

**I dont know why i am getting hydration errors**

2024-02-12 11:48 UTC, benjagm commented
Thanks for this PR @Min2who . Can you please describe what are you fixing? I am not sure what is not working as expected and the video has no explanation or voice so an additional explanation will be appreciated.

Thanks!!

2024-02-15 10:15 UTC, benjagm requested changes
Thanks a lot for your PR!!

I think the expected behaviour is to highlight just the title of the section your are visiting, no the one you are scrolling over, so the highlight will only happen when you actually click the section header, no when you mouse over what seems to be your implementation.

In addition I am getting some errors when testing your code (see attached):
<img width="1504" alt="Screenshot 2024-02-15 at 11 07 33" src="https://github.com/json-schema-org/website/assets/40007659/a6c9a4f4-2677-4faa-bbb1-3e65b2d4acb4">

Finally, I thinks the blue background is not ideal for highlight. I'll say will be better something more subtle. Maybe underline or adding an icon or emoji ...

2024-02-15 10:30 UTC, Min2who commented
> Thanks a lot for your PR!!
> 
> I think the expected behaviour is to highlight just the title of the section your are visiting, no the one you are scrolling over, so the highlight will only happen when you actually click the section header, no when you mouse over what seems to be your implementation.
> 
> In addition I am getting some errors when testing your code (see attached): <img alt="Screenshot 2024-02-15 at 11 07 33" width="1504" src="https://private-user-images.githubusercontent.com/40007659/305032851-a6c9a4f4-2677-4faa-bbb1-3e65b2d4acb4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5OTMyMjksIm5iZiI6MTcwNzk5MjkyOSwicGF0aCI6Ii80MDAwNzY1OS8zMDUwMzI4NTEtYTZjOWE0ZjQtMjY3Ny00ZmFhLWJiYjEtM2U2NWIyZDRhY2I0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE1VDEwMjg0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjMmI0YjAyYjY4YTg3ZTM5YWQzMmJlNGUzYjM1NjM4OWJkOWIzM2I2Yzg5NDZmMWZkODMyMDQ2YTRkNGQyYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KAA91XQyLVzeEScd2-2YRbn8FIr5UUpUjT2giBtw6Ck">
> 
> Finally, I thinks the blue background is not ideal for highlight. I'll say will be better something more subtle. Maybe underline or adding an icon or emoji ...

I will be working on it as soon as me exam get over. 🙇‍♂️

2024-02-24 14:25 UTC, benjagm commented
@Min2who remember you have this PR with some small changes to be added!

2024-02-25 15:02 UTC, Min2who commented
> In addition I am getting some errors when testing your code (see attached): <img alt="Screenshot 2024-02-15 at 11 07 33" width="1504" src="https://private-user-images.githubusercontent.com/40007659/305032851-a6c9a4f4-2677-4faa-bbb1-3e65b2d4acb4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4NzMyNDYsIm5iZiI6MTcwODg3Mjk0NiwicGF0aCI6Ii80MDAwNzY1OS8zMDUwMzI4NTEtYTZjOWE0ZjQtMjY3Ny00ZmFhLWJiYjEtM2U2NWIyZDRhY2I0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI1VDE0NTU0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiOTc4YjZkOWM0M2YxMTUyNThmM2Q5YTVhNDk5YmFlZDM2YzJjOTRlNWY2NWEwNDNhZGM4Mjc5NjA3ZWZhMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yDRDECDJEXP7rGc4kd-YOEK1VrN9tVPV_sE0YjtCifo">
> 
@benjagm after many trials of solving this error , I found that the error to be there from the start and occur even when i remove my changes it is still present 

Should i proceed with the PR of changes or what shall i do a comment will be appreciated

2024-02-26 17:48 UTC, benjagm commented
> @benjagm after many trials of solving this error , I found that the error to be there from the start and occur even when i remove my changes it is still present
> 
> Should i proceed with the PR of changes or what shall i do a comment will be appreciated

No sure what you mean here. Is your code fixing the bug? If yes push the code.

2024-02-26 23:20 UTC, benjagm commented
@DarhkVoyd can I ask you help with this PR? @Min2who seems to have issues with the code. Maybe you can take a look.
Thanks a lot for your support.

2024-02-27 03:07 UTC, DarhkVoyd commented
@benjagm Absolutely, I'd be happy to help out! I'll take a look and see if I can provide any assistance or guidance. Thanks for reaching out.

2024-02-27 04:34 UTC, DarhkVoyd commented
@benjagm The hydration issue is not related to this PR, the website already has multiple hydration issues originating from different sections in `Layout` and `Sidebar` components due to client side changes on server components. The production deployed website too displays minified errors for this in dev tools. Take a look: https://json-schema.org/learn/getting-started-step-by-step#overview

2024-02-27 04:38 UTC, DarhkVoyd commented
@Min2who you should probably proceed with the PR and make the changes requested in the last review.

2024-02-28 11:50 UTC, Min2who commented
https://www.loom.com/share/b9310a18a5744a26a125047b52c9af44?sid=6917409a-8c2a-4b11-81cb-1750d19e3f82

Done with the changes mentioned @benjagm

2024-02-28 12:35 UTC, benjagm commented
@Min2who You just submitted a new PR without addressing the [comment](https://github.com/json-schema-org/website/pull/304#pullrequestreview-1882362056) I did in my first review. I have been waring about being careful about pushing new PRs without addressing the review comments and without testing properly. This is time confusing and frustrating for others reviewing your code. 

At this point I am going to cancel this PR and leave the issue available for other contributor.
All reach out to you in a different message with more instructions.

2024-02-28 12:35 UTC, benjagm commented
https://github.com/json-schema-org/website/pull/304#issuecomment-1968891764

2024-02-28 13:10 UTC, Min2who commented
> @Min2who You just submitted a new PR without addressing the [comment](https://github.com/json-schema-org/website/pull/304#pullrequestreview-1882362056) I did in my first review. I have been waring about being careful about pushing new PRs without addressing the review comments and without testing properly. This is time confusing and frustrating for others reviewing your code.
> 

where is that new PR. If you find it please let me know @benjagm

2024-02-28 14:57 UTC, utnim2 commented
> I think the expected behaviour is to highlight just the title of the section your are visiting, no the one you are scrolling over, so the highlight will only happen when you actually click the section header, no when you mouse over what seems to be your implementation.
> 
> Finally, I thinks the blue background is not ideal for highlight. I'll say will be better something more subtle. Maybe underline or adding an icon or emoji ...

Your requested changes were addresed !
https://www.loom.com/share/b9310a18a5744a26a125047b52c9af44?sid=6917409a-8c2a-4b11-81cb-1750d19e3f82

2024-02-29 00:09 UTC, VivekJaiswal18 commented
@benjagm can I be assigned this issue. Thank you !

2024-02-29 12:32 UTC, DarhkVoyd commented
@benjagm Incase, we are unsure about the styles. How about something like [this](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#baseProtocol).

2024-03-01 12:33 UTC, benjagm commented
@DarhkVoyd and @utnim2 we'd love you to collaborate to complete this issue. DV can you please do the PR review and suggest changes to Mintu and as soon as this is working and approved as me for review? 

I need some extra hands to help me with the amount of PRs I have to review.

2024-03-01 12:43 UTC, DarhkVoyd commented
@benjagm Sure, I would love to help out. Any suggestions or advice on current status of the PR?

2024-03-01 12:45 UTC, benjagm commented
> Any suggestions or advice on current status of the PR? I'll take it from here and reach out once it's ready for your review.

You are doing the PR review: Just clone the repo and test it to is if works. If works review the code to see if all looks good... and if everything is ok may suggest some fine-tuning of the style.

2024-03-01 13:32 UTC, utnim2 commented
https://www.loom.com/share/87723b2cd1d2439dbc73495335c2fe3c?sid=b4fdac1a-4e6b-47b5-8c63-9d6adf31c0fc

The changes that i have made 

Cc @benjagm @DarhkVoyd

2024-03-02 07:13 UTC, DarhkVoyd requested changes
Nice work with this one, the code works nicely. I added some comments please check them. Also,
- I believe your editor's formatter has auto-formatted code on save. Let's keep our PRs focused on the changes that we are intentionally making to avoid adding unnecessary noise.
- I somewhat agree with your current highlighting approach but I believe it's not enough let's make it bit more visible. What do you think? How about a subtle grey background?

2024-03-02 07:13 UTC, DarhkVoyd commented on components/Headlines.tsx
> -      const slug = slugifyMarkdownHeadline(children as any[])
Here, the previous implementation states 
> // recalculation necessary because of scope issue

This PR changes it, why is it no longer necessary

2024-03-02 08:51 UTC, DarhkVoyd commented
I agree with @benjagm's suggestion, however, I'm concerned readers might still miss it.  Could we experiment with a slightly lighter background color like a subtle shade of grey? Or perhaps a combination of a light background and underlined text? What do you think?

2024-03-04 03:33 UTC, divyaxdv commented
> I agree with @benjagm's suggestion, and I even missed the highlight initially. I'm concerned readers might have the same problem. Could we experiment with a slightly lighter background color like a subtle shade of grey? Or perhaps a combination of a light background and underlined text? What do you think?

I think the changes does its part pretty well, but I agree a little can be improvised like a background to make the fragment more distinguished.

2024-03-08 09:58 UTC, benjagm commented
@utnim2 can you please rebase and fix the merge conflicts please? I'll make a another review.

2024-03-22 14:00 UTC, benjagm commented
We are closing this PR as we didn't receive response.

2024-03-22 14:00 UTC, closed without merging

2024-03-22 15:53 UTC, utnim2 commented
Sorry for that @benjagm , I will help to review the PR