fixed lazy expression issue
json-schema-org/website pull request #325
Opened 2024-02-22 13:29 UTC by Sanket-0510

**GitHub Issue:** #188 

**Summary**:

**Do you think resolving this issue might require an [Architectural Decision Record (ADR)](https://github.com/json-schema-org/community/blob/main/CONTRIBUTING.md#key-architectural-decisions)? (significant or noteworthy)**

No
its a small fix, which solves the lazy expression issue

2024-02-26 18:17 UTC, benjagm commented
@gregsdennis Can you please help my reviewing if the proposed solution is ok?

2024-02-26 18:22 UTC, gregsdennis commented
Please hold. I have a question in the issue. This may not be necessary.

2024-02-27 22:36 UTC, gregsdennis approved these changes
Discussion in issue.

2024-02-27 22:41 UTC, benjagm approved these changes

2024-02-28 03:05 UTC, karenetheridge requested changes

2024-02-28 03:05 UTC, karenetheridge commented on pages/understanding-json-schema/reference/regular_expressions.md
> +-   `{x,y}?`, `{x,}?`: Lazy versions of the above expressions.
```suggestion
-   `{x,y}?`, `{x,}?`: Non-greedy versions of the above expressions.
```

While we're here, I'd like to make this fix (it's the only occurrence in the file).

2024-02-28 03:05 UTC, karenetheridge commented on pages/understanding-json-schema/reference/regular_expressions.md
> +-   `{x,y}?`, `{x,}?`: Lazy versions of the above expressions.
Otherwise, your edit is correct.

2024-02-29 17:59 UTC, karenetheridge approved these changes

2024-03-02 14:19 UTC, merged