Header size reduced when outside landing page.
json-schema-org/website pull request #333
Opened 2024-02-22 21:32 UTC by deveshidwivedi

**GitHub Issue:** #52

**Summary**:
The header now is reduced in size for all the pages except the landing page, as mentioned in the issue. 

**Do you think resolving this issue might require an [Architectural Decision Record (ADR)](https://github.com/json-schema-org/community/blob/main/CONTRIBUTING.md#key-architectural-decisions)? (significant or noteworthy)**

No

2024-02-22 21:40 UTC, deveshidwivedi commented
Please let me know if other changes are required, thank you!

2024-02-23 01:09 UTC, benjagm requested changes
Thanks a lot for this PR!

This was a first good step, however I think we need some more adjustments to produce the best result.

2024-02-23 01:09 UTC, benjagm commented on components/Layout.tsx
> +          <header className={classnames('w-full bg-white fixed top-0 z-[170] shadow-xl',  { 'h-16': !isLandingPage, 'drop-shadow-lg': isLandingPage, 'shadow-sm': !isLandingPage })}>
<img width="1508" alt="Screenshot 2024-02-23 at 02 05 41" src="https://github.com/json-schema-org/website/assets/40007659/e072127a-ab9f-4254-a1ba-3f663c0bac55">

This is what I see. I think we need to reduce the space on top and try to center the elements vertically to have the same space between the top and the bottom. We can also reduce the size of the logo.

We should check the mobile versión too.

2024-02-23 10:41 UTC, benjagm requested changes
![Screenshot 2024-02-23 at 11 37 37](https://github.com/json-schema-org/website/assets/40007659/e13a2c5a-2b8d-4462-9be5-f5969271bd18)

Looks better! However we have now a lot of unused space between the header and the sidebar and the content. We need to move the content upper.

2024-02-24 18:38 UTC, deveshidwivedi commented
hi @benjagm! does this look okay?

2024-02-24 20:42 UTC, benjagm commented
> hi @benjagm! does this look okay?

I don't see any change. We need to decrease that huge space between the header and the content.

2024-02-26 18:57 UTC, benjagm commented
@deveshidwivedi let me know if you need help with this one!

2024-02-27 00:11 UTC, deveshidwivedi commented
Sorry for the delay @benjagm. I have reduced the padding on top and margin on bottom (to make it look even), please let me know if it can get better, thanks.

2024-02-27 17:28 UTC, benjagm commented
> I have reduced the padding on top and margin on bottom (to make it look even), please let me know if it can get better, thanks.

You will need to move the sidebar up as well. (You only moved the page's body)

2024-02-27 17:28 UTC, benjagm requested changes
You will need to move the sidebar up as well. (You only moved the page's body)

2024-02-28 15:14 UTC, benjagm approved these changes
Nice job @deveshidwivedi!! Looks great!

Can you take a look to the conflict in components/Layout.tsx? Probably many changes since you created the fork.

Thanks a lot!

2024-02-29 12:33 UTC, deveshidwivedi commented
done!

2024-03-01 09:33 UTC, benjagm commented
Thanks @deveshidwivedi !! When doing the last test before merging I found something we need to fix in mobile.
This is what we have in this PR:
<img width="303" alt="Screenshot 2024-03-01 at 10 31 34" src="https://github.com/json-schema-org/website/assets/40007659/132c1f2f-64d9-43e7-81b1-33a9e1734047">

But this is what we should have:
<img width="305" alt="Screenshot 2024-03-01 at 10 31 50" src="https://github.com/json-schema-org/website/assets/40007659/3c51826c-840f-439f-926a-6b991e0046bd">

We need to do the correction in mobile too to move the content up.

2024-03-01 16:10 UTC, deveshidwivedi commented
updated!

2024-03-03 15:44 UTC, benjagm commented
Thanks @deveshidwivedi Can you please sqash and rebase ? We'll merge this.

2024-03-06 10:14 UTC, deveshidwivedi commented
I think I'll open another PR for this @benjagm. I'm sorry!

2024-03-06 10:14 UTC, closed without merging