Fix Inconsistent code rendering in documentation examples
json-schema-org/website pull request #356
Opened 2024-02-25 04:33 UTC by Sahil-Shadwal

**GitHub Issue:** #349 

**Summary**:
The documentation inconsistent code rendering examples have been fixed.

**Do you think resolving this issue might require an [Architectural Decision Record (ADR)](https://github.com/json-schema-org/community/blob/main/CONTRIBUTING.md#key-architectural-decisions)? (significant or noteworthy)**

No

2024-02-25 09:54 UTC, DarhkVoyd commented
Thanks for this. I'll review the changes soon. Meanwhile, please link this PR to the original issue.
Reference: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

2024-02-26 10:13 UTC, DarhkVoyd requested changes
Hey, Thank you for this one. Kindly, review on my comments.
1. I believe your editor's markdown linter has changed certain parts of the markdown. Namely, changing `*` to `-` and changing floating point numbers such as `12.50` to `12.5` and some of the indentation. They should not be a part of the PR, kindly revert those.
2. Your approach is mostly valid, but the goal of previous syntax was to demonstrate that the json key is being built upon the previous step's json key or the schema object itself so that it is clearly visible that those are relative and nested changes. This is no longer explicit. We could use some more `...` to make it explicit. 
3. Lastly, if possible show "json" instead of "data".

2024-02-27 06:45 UTC, DarhkVoyd commented
@benjagm Since, the solution involves closing the json, I think we still need to add some `...` so that its abundantly clear that we are building on top of certain sections of schema. Also, I am waiting for an update about `data` to `json`.

2024-02-27 09:52 UTC, Sahil-Shadwal commented
Okay will revert those .

2024-02-27 10:33 UTC, DarhkVoyd commented
@Sahil-Shadwal Let's wait for the maintainers opinion on my suggestions.

2024-02-27 10:48 UTC, benjagm commented
Thanks everyone!!

Why changing the format of the list to use '-' instead '*'? That has nothing to do with the issue and doesn't fix anything.

Regarding the '...' that is true @DarhkVoyd . We need to keep them there.

2024-02-27 11:59 UTC, Sahil-Shadwal commented
Sorry about * to - it got auto changed when i saved the file , let me correct that . Is there anything else?

2024-02-27 12:04 UTC, DarhkVoyd commented
@Sahil-Shadwal Kindly refer to my previous review. Regarding `...`, please add `...` at appropriate places to ensure that it's abundantly clear that we are building on top of certain sections of schema and clearly express its structure. 

> Hey, Thank you for this one. Kindly, review on my comments.
> 
> 1. I believe your editor's markdown linter has changed certain parts of the markdown. Namely, changing `*` to `-` and changing floating point numbers such as `12.50` to `12.5` and some of the indentation. They should not be a part of the PR, kindly revert those.
> 2. Your approach is mostly valid, but the goal of previous syntax was to demonstrate that the json key is being built upon the previous step's json key or the schema object itself so that it is clearly visible that those are relative and nested changes. This is no longer explicit. We could use some more `...` to make it explicit.
> 3. Lastly, if possible show "json" instead of "data".

2024-02-27 20:03 UTC, gregsdennis commented on pages/learn/getting-started-step-by-step.md
> -"title": "Product",
If we're going to make these syntax-highlighted, we need to do this differently.

    ```jsonc
    // ...
    "title": "Product",

`jsonc` allows comments, and I'm pretty sure we can get it to have the same highlight colors as `json` (probably in another PR if it's not already that way)

2024-02-27 20:08 UTC, gregsdennis requested changes
I think we need to re-evaluate the importance of having proper JSON.  I'm not sure it's needed.  More important than the snippets being "correct" is that they are understandable.  I think many of these edits serve to confuse the reader rather than clarifying the ideas that the narrative is trying to convey.

2024-02-27 20:08 UTC, gregsdennis commented on pages/learn/getting-started-step-by-step.md
>  }
Similarly, this isn't the full schema on its own.  The current snippet (although not proper JSON) demonstrates well that this is an excerpt from the above schema, but the new snippet is a schema by itself.

This is seen in a lot of these changes.

2024-02-27 20:08 UTC, gregsdennis commented on pages/learn/getting-started-step-by-step.md
> +{
like here

2024-02-27 20:08 UTC, gregsdennis commented on pages/learn/getting-started-step-by-step.md
> +  "dimensions": {
here

2024-02-27 20:08 UTC, gregsdennis commented on pages/learn/getting-started-step-by-step.md
> +  "dimensions": {
and here

2024-02-27 20:35 UTC, Sahil-Shadwal commented
Thanks for the review, will surely look into it . But it is getting confusing, should i revert back  the changes ?

2024-02-28 05:53 UTC, DarhkVoyd commented
@gregsdennis Hey, I am bit confused. As per my understanding, we agree on:

> The current snippet (although not proper JSON) demonstrates well that this is an excerpt from the above schema, but the new snippet is a schema by itself.

So are we against closing the json as a solution, or the usage of `...` or the entire approach.

2024-02-28 06:47 UTC, gregsdennis commented
I'm happy to have the `...`, but the changes look like they're trying to create full JSON values, which isn't right.

It looks like the code blocks already have the language specifier.  I'm guessing the bare `...` is causing them to be rendered as plain text.

I think if we change the language specifier to `jsonc` and use `// ...` it _might_ render right.

Otherwise we'll have to do something like

    ```jsonc
    {
      // ...
      "properties": {
        // ...
        "newProperty": {}
      }
    }
    ```

Then we need to make sure the `jsonc` formatting is the same as the `json` formatting.

2024-02-28 07:17 UTC, DarhkVoyd commented
Yes, that's what I meant. You explained it better.

2024-03-08 10:41 UTC, benjagm commented
@Sahil-Shadwal is this ready to review? Thanks a lot!

2024-03-11 13:02 UTC, closed without merging

2024-03-11 17:56 UTC, gregsdennis commented
@Sahil-Shadwal was this replaced by another PR? Could you link to it, please?

2024-03-11 18:00 UTC, DarhkVoyd commented
This was replaced with this PR:  https://github.com/json-schema-org/website/pull/475