fix: #366  Resolve the icon size bug under the "Supported by" section
json-schema-org/website pull request #372
Opened 2024-02-27 04:19 UTC by officeneerajsaini

In this issue, I addressed a bug related to icon sizes. I observed that the Slack icon had a larger height compared to the common room icon. To rectify this issue, I applied a scaling property to ensure uniform icon sizes.

This enhancement is crucial for maintaining a visually consistent and polished appearance across the platform. The "before" and "after" screenshots provide a clear visual representation of the improvement.

**GitHub Issue:**  fix #355 

**Summary**:
before :
![Screenshot from 2024-02-26 21-37-38](https://github.com/json-schema-org/website/assets/118799941/a7bfdc1f-2e67-407b-b182-d836d3042fcb)

after :
![Screenshot from 2024-02-27 09-44-16](https://github.com/json-schema-org/website/assets/118799941/ad3bc4bf-6c87-403e-9cc1-c2fe72626178)

2024-02-27 04:23 UTC, officeneerajsaini commented
![Screenshot from 2024-02-27 09-52-40](https://github.com/json-schema-org/website/assets/118799941/bb00e707-1065-40ec-8cc9-5d46d76e55f1)

2024-02-27 04:35 UTC, officeneerajsaini commented
![Screenshot from 2024-02-27 10-02-43](https://github.com/json-schema-org/website/assets/118799941/2d986625-ca45-43a8-a39a-f0b629b7f03b)

2024-02-28 10:27 UTC, benjagm requested changes
I think we need to check how the 2 logos centers horizontally. It seems the space in the right side is bigger.

<img width="930" alt="Screenshot 2024-02-28 at 11 20 44" src="https://github.com/json-schema-org/website/assets/40007659/30c6a76e-8034-4b57-abab-c34dda0140e4">

2024-02-28 16:15 UTC, officeneerajsaini commented
![Screenshot from 2024-02-28 21-42-01](https://github.com/json-schema-org/website/assets/118799941/7099c80a-cadd-44f5-b5c4-2a25a609c548)

![Screenshot from 2024-02-28 21-44-27](https://github.com/json-schema-org/website/assets/118799941/66cfbfc5-20e0-43f0-b3ee-56757c83b696)

![Screenshot from 2024-02-28 21-44-45](https://github.com/json-schema-org/website/assets/118799941/a50fb69f-51fa-42de-9e66-dcc5d4ab586f)

2024-02-28 17:02 UTC, benjagm approved these changes
Looks great @officeneerajsaini !! Approve from side. 

Excellent job.

2024-02-29 10:34 UTC, merged