resolved code formatting issue #371
json-schema-org/website pull request #385
Opened 2024-02-28 12:56 UTC by Adity20

2024-02-28 20:11 UTC, gregsdennis requested changes

2024-02-28 20:11 UTC, gregsdennis commented on pages/draft/2020-12/release-notes.md
> +      // strict-tree schema, guards against misspelled properties
Looks like there's still an issue with syntax highlighting. Probably is this comment.

Can you change the language specifier to `jsonc` to see if that fixes the issue?

2024-02-29 03:03 UTC, Adity20 commented
Sure @gregsdennis I'll try that too.

2024-02-29 11:05 UTC, Adity20 commented
Hi @gregsdennis  I have tried some changes and now the UI looks like this 
![Screenshot 2024-02-29 163342](https://github.com/json-schema-org/website/assets/119804372/ee1ed189-d850-4b05-a909-47dde4db4102)
![Screenshot 2024-02-29 163351](https://github.com/json-schema-org/website/assets/119804372/b1384670-5a6c-475b-a0e4-534cc3be44cb)
kindly review it and let me know if some more changes are required

2024-03-01 19:36 UTC, gregsdennis requested changes

2024-03-02 05:48 UTC, Adity20 commented on pages/draft/2020-12/release-notes.md
> +        {
sure @gregsdennis i'll make the changes asap

2024-03-02 06:02 UTC, Adity20 commented on pages/draft/2020-12/release-notes.md
> +        {
can you check now @gregsdennis

2024-03-02 06:04 UTC, gregsdennis commented on pages/draft/2020-12/release-notes.md
> +        {
Did you push the changes?  I don't see a difference in the code.  Also, could you provide a screenshot? I can't run the site locally.

2024-03-02 06:18 UTC, Adity20 commented on pages/draft/2020-12/release-notes.md
> +        {
but at my end its showing the changes

2024-03-02 06:20 UTC, Adity20 commented on pages/draft/2020-12/release-notes.md
> +        {
here are the screenshots 
![Screenshot 2024-03-02 114910](https://github.com/json-schema-org/website/assets/119804372/8f10430a-5de6-4b23-8fcf-3aee9e018428)
![Screenshot 2024-03-02 114924](https://github.com/json-schema-org/website/assets/119804372/f16eac2a-e817-4ebf-b79d-0cd7457cac1d)
![Screenshot 2024-03-02 114939](https://github.com/json-schema-org/website/assets/119804372/d897d7e7-6575-4f4b-aa56-1f75c5fa59a6)

and the output of these changes 
![Screenshot 2024-02-29 163342](https://github.com/json-schema-org/website/assets/119804372/4d8390eb-51f0-41db-adb4-5806f2764086)
![Screenshot 2024-02-29 163351](https://github.com/json-schema-org/website/assets/119804372/7bed0a0b-7d86-4e25-9950-e1691210cd31)

2024-03-02 06:22 UTC, Adity20 commented
If you are not able to see these new changes then I can close this pr and push the changes again by opening another pull request all changes at once if thats fine?

2024-03-02 08:34 UTC, gregsdennis commented on pages/draft/2020-12/release-notes.md
> +        {
I don't see the indention changes I asked for.  This is what's confusing.

Please move the JSON all the way to the left, ignoring the HTML indentation.

2024-03-02 08:40 UTC, Adity20 commented on pages/draft/2020-12/release-notes.md
> +        {
Now fine @gregsdennis ?
![Screenshot 2024-03-02 140956](https://github.com/json-schema-org/website/assets/119804372/f4daef1c-1f8d-4ce2-bd6c-5ce51d34a482)

2024-03-02 16:45 UTC, Adity20 commented
Hi @gregsdennis I changed the format to jsonc and now the output looks like this kindly check 
![Screenshot 2024-03-02 221450](https://github.com/json-schema-org/website/assets/119804372/706afc31-65c1-4459-891e-870200f0e22c)

2024-03-02 19:21 UTC, gregsdennis commented on pages/draft/2020-12/release-notes.md
> +        {
There's still some indention.  Please pull _all the way_ to the left.

<img width="412" alt="image" src="https://github.com/json-schema-org/website/assets/2676804/e3e960ae-304f-4644-989b-bfdb368c1628">

2024-03-02 19:25 UTC, gregsdennis commented
What's going on here?

<img width="288" alt="image" src="https://github.com/json-schema-org/website/assets/2676804/e275ce0d-a264-48b9-9d14-f86edb16463a">

Also, the indentation seems to have been messed up on the 2020-12 and completely removed on the 2019-09.  It's almost as if it's rendering spaces with variable width.

![image](https://github.com/json-schema-org/website/assets/2676804/89980ac0-0c3c-4bd4-97fd-34639efdb616)

This is very confusing; the code looks fine to me.

2024-03-03 03:06 UTC, Adity20 commented
Now fine @gregsdennis ?
![Screenshot 2024-03-03 083545](https://github.com/json-schema-org/website/assets/119804372/8db0f0c7-bb41-413f-a553-f7ba5690881d)

2024-03-03 03:11 UTC, gregsdennis commented
The code looks good, but it still doesn't render right.  The code has the correct indentation, but the render shows none.

2024-03-03 03:15 UTC, Adity20 commented
So what should I do now?

2024-03-03 10:17 UTC, benjagm commented
Maybe this is related with the problems here:

There are 2 config attributes in the code editor I needed to change to avoid extra width of the containing page for some scenarios for small devices, but the solution was suboptimal. I think this is related. Below the commit I did:
https://github.com/json-schema-org/website/commit/cd3078604f28ecc1e9c3ad292e399b06cc97c17c

related (maybe): https://github.com/react-syntax-highlighter/react-syntax-highlighter/issues/376

2024-03-03 11:07 UTC, Adity20 commented
Is this for issue #393?

2024-03-03 11:08 UTC, Adity20 commented
> Maybe this is related with the problems here:
> 
> There are 2 config attributes in the code editor I needed to change to avoid extra width of the containing page for some scenarios for small devices, but the solution was suboptimal. I think this is related. Below the commit I did: [cd30786](https://github.com/json-schema-org/website/commit/cd3078604f28ecc1e9c3ad292e399b06cc97c17c)
> 
> related (maybe): [react-syntax-highlighter/react-syntax-highlighter#376](https://github.com/react-syntax-highlighter/react-syntax-highlighter/issues/376)

Is this for issue #393 @benjagm ?

2024-03-03 11:10 UTC, Adity20 commented
> Maybe this is related with the problems here:
> 
> There are 2 config attributes in the code editor I needed to change to avoid extra width of the containing page for some scenarios for small devices, but the solution was suboptimal. I think this is related. Below the commit I did: [cd30786](https://github.com/json-schema-org/website/commit/cd3078604f28ecc1e9c3ad292e399b06cc97c17c)
> 
> related (maybe): [react-syntax-highlighter/react-syntax-highlighter#376](https://github.com/react-syntax-highlighter/react-syntax-highlighter/issues/376)

So what new changes I need to introduce @benjagm ?

2024-03-03 11:25 UTC, benjagm commented
The problem is with indentation right? Those 2 parameters affects exactly that. First play with them, later well need to check how to make sure the  component's behavior is correct in other pages, specifically in small devices.

2024-03-03 11:31 UTC, Adity20 commented
Okay @benjagm I'll try that too.

2024-03-04 18:24 UTC, benjagm commented
@Adity20 did you tested the component indentation disabling the attributes wrapLines and wrapLongLines? I think that can fix it.

2024-03-05 06:30 UTC, Adity20 commented
I tried disabling these two attributes and tried some other changes too but that's creating an overflow in the page as the code is taking more space now to be in the same line. 
I don't think this will work we'll have to apply more custom styles maybe

2024-03-05 07:05 UTC, benjagm commented
> Can we have each section scroll horizontally? Would it be weird to have that here but not in other places?
> 
> Alternatively, what if we made it look like a git diff, where you do a red `-` line followed by a green `+`line? Is that possible?

I'd suggest fix everything but the indentation issue here and create an different issue to configure the code component to have its own horizontal scroll bar se fix this across the entire site.

2024-03-05 07:12 UTC, gregsdennis commented
I'm happy with that

2024-03-05 09:57 UTC, Adity20 commented
So I should try horizontal scrollbar once or keep trying some other changes?

2024-03-05 16:30 UTC, benjagm commented
@Adity20 I think si better to do it in a separate issue. Let suggest this:

- Let's approve this leaving the indentation unfixed.
- I'll open the issue and assign it to you if this is ok for you.

2024-03-05 16:30 UTC, benjagm approved these changes
Great job @Adity20 !!!

2024-03-05 16:47 UTC, Adity20 commented
Yeah that works for me @benjagm. I can start working on the that one then.

2024-03-05 17:34 UTC, benjagm commented
@Adity20 please add a comment in https://github.com/json-schema-org/website/issues/456 to get assigned.

2024-03-05 20:01 UTC, gregsdennis approved these changes
Everything except the indentation seems to be resolved.  I'm happy address that elsewhere.

2024-03-05 23:35 UTC, merged