Adding Docker Setup/
json-schema-org/website pull request #387
Opened 2024-02-28 17:27 UTC by DhairyaMajmudar

**GitHub Issue:** #378 

**Summary**:

1. Dockerised the setup by adding docker file for creating the images and run those images in docker containers.
2. Added make commands to shorten those commands and can be used easily by developers.

**Do you think resolving this issue might require an [Architectural Decision Record (ADR)](https://github.com/json-schema-org/community/blob/main/CONTRIBUTING.md#key-architectural-decisions)? (significant or noteworthy)**

Yes

2024-02-28 17:30 UTC, DhairyaMajmudar commented
@benjagm I have added the docker setup for codebase.

You can check the work by following 
1. Running `make install` command for creating docker images.
2. Running `make run` command for running the website in `localhost:3000`

2024-02-29 10:09 UTC, benjagm approved these changes
Can we modify the readme to tell the users that **they have the option** to use docker as well?

2024-02-29 10:10 UTC, benjagm requested changes
Can we modify the readme to explain users that they have the option of using dokcer if they prefer it?

2024-02-29 14:13 UTC, DhairyaMajmudar commented
@benjagm I have added the docker installation guide in the readme pls. have a look : )

2024-03-01 10:11 UTC, benjagm requested changes
Looks good. Just left the last suggestion to make it clear that docker is just another option to run it.

2024-03-01 10:11 UTC, benjagm commented on README.md
> +### Run locally using Docker
```suggestion
### Run locally using Docker

If you are a Docker lover, you have the option to use it following these instructions.
```

2024-03-01 11:27 UTC, DhairyaMajmudar commented
Thanks you suggestion , I have committed it.

2024-03-01 12:57 UTC, benjagm approved these changes

2024-03-01 12:57 UTC, benjagm commented
Good job here!

2024-03-01 12:58 UTC, merged