Issue 412
json-schema-org/website pull request #420
Opened 2024-03-03 11:59 UTC by TamannaVerma99

**What kind of change does this PR introduce?**
A bugfix

**Issue Number:**
412

**Summary**
I've made appropriate improvements to the CSS properties of the blog landing page to ensure responsiveness across all screen sizes. Additionally, I've enhanced the picture size on the landing page for better visual appeal and readability. These changes aim to create a more user-friendly and visually engaging experience for visitors accessing the blog.

2024-03-03 15:48 UTC, officeneerajsaini commented
Mention #412 in your pr it will add on that issue pr , so maintainer can review or understand easily .., it can make easy to access

2024-03-03 16:55 UTC, DhairyaMajmudar reviewed
That's an amazing pr @TamannaVerma99 but can you pls. remove unwanted changes done by prettier extension so that it will be easy for maintainers to review the actual changes.

Also pls. add pr title suggesting the changes done. 

Thank You : )

2024-03-03 18:03 UTC, aialok commented
> That's an amazing pr @TamannaVerma99 but can you pls. remove unwanted changes done by prettier extension so that it will be easy for maintainers to review the actual changes.
> 
> Also pls. add pr title suggesting the changes done.
> 
> Thank You : )

@TamannaVerma99 , If you remove prettier changes then it will throw eslint error. Make sure you have fetch the latest changes before working on issue.
Once you fetch the latest changes you will not get any additional lines change.

Thank You  : )

2024-03-03 18:08 UTC, TamannaVerma99 commented
Thank you so much for your suggestions, Really appreciate them!
However, I believe using Prettier for such Code Bases definitely counts in as one of the good coding practices. Infact, we should have Prettier & EsLint configured already in the code base to encourage them :)

2024-03-03 18:15 UTC, aialok commented
> Thank you so much for your suggestions, Really appreciate them! However, I believe using Prettier for such Code Bases definitely counts in as one of the good coding practices. Infact, we should have Prettier & EsLint configured already in the code base to encourage them :)

Basically we do already setup the prettier and eslint. Just fetch the latest changes : )

2024-03-04 12:49 UTC, benjagm requested changes
Mobile looks great. For desktop there is a great improvement but I think we'll need to move the element down in the vertical axis to have them centered vertical. See image.
<img width="811" alt="Screenshot 2024-03-04 at 13 47 14" src="https://github.com/json-schema-org/website/assets/40007659/104f0c24-c853-4c85-b441-3895b380a37c">

We need the same height in the arrow on top and in the arrow in the bottom.

2024-03-04 14:31 UTC, TamannaVerma99 commented
okay ,I will do  the required! Thanks for the feedback :)

2024-03-04 17:42 UTC, TamannaVerma99 commented
Made the required changes @benjagm . The text is now aligned at the center for desktop view. However, it is quite improbable to do the same on all screen sizes, given the inclined nature of the image. But have tried my best to ensure appropriate text alignment accordingly on all remaining screen sizes.

2024-03-05 14:27 UTC, TamannaVerma99 commented
@benjagm can you please have a look on it?

2024-03-05 14:33 UTC, benjagm commented on tailwind.config.js
> +    screens: {
Is this code necessary?

2024-03-05 14:35 UTC, benjagm approved these changes
Looks great. Just left a comment regarding editing tailwind.config.js. I am not sure if the new code there is necessary.

2024-03-05 15:21 UTC, TamannaVerma99 commented
@benjagm in order to add custom screen sizes in Tailwind, its necessary to specify the default screen sizes as well to prevent overwriting them. So, needed to add them as well along with the new custom size (ab1 :'890px')

2024-03-05 15:35 UTC, merged

2024-03-05 16:07 UTC, aialok commented
Hey @TamannaVerma99, it seems like you haven't formatted the code with Prettier. Now, when I fetch the latest changes, I'm getting ESLint errors for the file you've edited. Did you bypass the Husky pre-commit checks? 

I think you should format and check for ESLint errors before pushing your code. Otherwise, it could create problems for other contributors who are working on the project.

![Screenshot from 2024-03-05 21-27-27](https://github.com/json-schema-org/website/assets/66772290/617aef00-0648-40e2-8e73-1a1a20448389)
![Screenshot from 2024-03-05 21-27-06](https://github.com/json-schema-org/website/assets/66772290/95678496-4c2f-4718-a1ce-d618839d8adf)

Well, we've recently implemented a PR workflow where we check formatting, ESLint, and type checking. This should prevent this type of issues in the future.

@benjagm, this needs to be fixed as soon as possible. You can either revert this PR or fix the issue from your end.

Thank you : )

2024-03-05 17:24 UTC, benjagm commented
Fixed in production. Thanks everyone.