remove padding from top issue#414
json-schema-org/website pull request #422
Opened 2024-03-03 14:56 UTC by Ali7040

**What kind of change does this PR introduce?**
Unnecessary top padding and block property.

**Issue Number:**
-  Closes #414 
-  Related to #___ 
-  Others? 

**Screenshots/videos:**

<img width="1022" alt="Screenshot 2024-03-03 at 7 53 06 PM" src="https://github.com/json-schema-org/website/assets/81979505/6d6ddb02-56dd-4951-b00e-dba5b72ed183">

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

2024-03-03 18:55 UTC, DhairyaMajmudar approved these changes
LGTM : D 
Suggested some changes to resolve vs code warnings.

2024-03-03 18:55 UTC, DhairyaMajmudar commented on pages/index.page.tsx
> +                  className='block w-full lg:w-1/2 rounded border-2 bg-primary text-white  h-[40px] text-center flex items-center justify-center'
```suggestion
                  className='w-full lg:w-1/2 rounded border-2 bg-primary text-white  h-[40px] text-center flex items-center justify-center'
```

2024-03-03 18:57 UTC, DhairyaMajmudar commented on pages/index.page.tsx
> +                  className='block w-full lg:w-1/2 rounded border-2 bg-primary text-white  h-[40px] text-center flex items-center justify-center'
pls. also remove `leading-5` from line 242 reason same resolving vscode warnings.

2024-03-04 12:57 UTC, benjagm requested changes
Great job @Ali7040 . Can you please implement or resolve the suggestions made by @DhairyaMajmudar ?

2024-03-04 14:46 UTC, Ali7040 commented
> Great job @Ali7040 . Can you please implement or resolve the suggestions made by @DhairyaMajmudar ?

sure!

2024-03-04 14:51 UTC, Ali7040 commented on pages/index.page.tsx
> +                  className='block w-full lg:w-1/2 rounded border-2 bg-primary text-white  h-[40px] text-center flex items-center justify-center'
Done.

2024-03-04 16:00 UTC, benjagm commented
Thanks everyone! Is this ready to review again?

2024-03-05 13:57 UTC, Ali7040 commented
> Thanks everyone! Is this ready to review again?

yes!

2024-03-05 14:57 UTC, merged