Fix: draft behaviour and hydration error
json-schema-org/website pull request #498
Opened 2024-03-10 04:34 UTC by AdityaSingh-02

**What kind of change does this PR introduce?**

**Issue Number:**

-  Closes #483  #487  
-  Related to #___ 
-  Others? 

**Screenshots/videos:**

**Before**

https://github.com/json-schema-org/website/assets/94185167/5a59b99d-f71f-4855-814e-6cbf271dff91

**After**

https://github.com/json-schema-org/website/assets/94185167/9a33a0ff-bf5a-471f-aeb6-df5fd49d8c7a

**If relevant, did you update the documentation?**

**Summary**
1- Here I have fixed the behavior of the table before it was taking full width and there was not any overflow or width property.
2- I have also made changes in the release-notes.md, which was causing a hydration error and  I made a change at line number 466. it was taking more than required width.

**Does this PR introduce a breaking change?**
- No

2024-03-10 06:05 UTC, DhairyaMajmudar reviewed
Can you pls. remove the changes from yarn.lock and package.lock.json file since it is increasing the pr size.

2024-03-10 06:08 UTC, DhairyaMajmudar commented
Also it will be good for users, if instead of applying overflow-auto , the 1x2 grid is converted into 2x1 grid as suggested in the issue : )

2024-03-10 14:49 UTC, JeelRajodiya requested changes
I think you deleted the entire yarn.lock file. 
As @DhairyaMajmudar mentioned, please leave the yarn.lock file as it is ( do not make any changes nor delete it  )

2024-03-10 15:04 UTC, AdityaSingh-02 commented
> I think you deleted the entire yarn.lock file. As @DhairyaMajmudar mentioned, please leave the yarn.lock file as it is ( do not make any changes nor delete it )

Yup, I deleted it completely(by mistake), I should have stashed changes before pushing, I will take care of it from next time, Till then what should I do? will it affect the code? since I have not added any new dependencies, the file has minor changes it should not affect code base(I might be wrong here)

2024-03-10 15:06 UTC, aialok commented
@AdityaSingh-02, a better approach would be to clone the project from the beginning using Yarn and leave this as it is. Check out the `README.md` for more details. 
Then, create a new branch with the same name as the one you used in this PR and make the required changes or you can copy-paste your work and force-push the changes to this PR branch. This will solve all your problems. Before cloning the project again, make sure you have fetched the latest upstream in your fork repository to avoid any conflict.

2024-03-10 15:12 UTC, AdityaSingh-02 commented
Heyy @JeelRajodiya I have reverted the changes, could you look at it again?

2024-03-10 15:46 UTC, JeelRajodiya commented
@AdityaSingh-02, are you using npm ?

2024-03-10 15:47 UTC, AdityaSingh-02 commented
> @AdityaSingh-02, are you using npm ?

yup

2024-03-10 15:52 UTC, JeelRajodiya commented
> > @AdityaSingh-02, are you using npm ?
> 
> yup

yes, that is why the yarn.lock file is being modified. 

You'll have **use yarn** instead of npm as suggested by @aialok in [this](https://github.com/json-schema-org/website/pull/498#issuecomment-1987263107) comment

2024-03-10 15:53 UTC, AdityaSingh-02 commented
> > > @AdityaSingh-02, are you using npm ?
> > 
> > 
> > yup
> 
> yes, that is why the yarn.lock file is being modified.
> 
> You'll have **use yarn** instead of npm as suggested by @aialok in [this](https://github.com/json-schema-org/website/pull/498#issuecomment-1987263107) comment

okay got it, so should I do everything again or this works?

2024-03-10 15:57 UTC, JeelRajodiya commented
> > > > @AdityaSingh-02, are you using npm ?
> > > 
> > > 
> > > yup
> > 
> > 
> > yes, that is why the yarn.lock file is being modified.
> > You'll have **use yarn** instead of npm as suggested by @aialok in [this](https://github.com/json-schema-org/website/pull/498#issuecomment-1987263107) comment
> 
> okay got it, so should I do everything again or this works?

can you run `yarn install` command and let me know if the yarn.lock file changes or not?

2024-03-10 16:17 UTC, AdityaSingh-02 commented
Heyy @aialok @JeelRajodiya Thank you for your guidance, I followed your steps and pushed changes using yarn, and this time yarn.lock file didn't change

2024-03-11 09:12 UTC, JeelRajodiya approved these changes

2024-03-11 09:15 UTC, JeelRajodiya commented
Hey @AdityaSingh-02, You have resolved the problem. 
but I want to bring this section of the #483 to your attention. 
![image](https://github.com/json-schema-org/website/assets/63534268/34dcb9ad-be72-4104-9cbd-45ed7f8baee7)


Let's just wait for the maintainer's review

2024-03-11 10:46 UTC, benjagm commented
It is not the solution I proposed but I like it. Thanks!

2024-03-11 10:46 UTC, benjagm approved these changes

2024-03-11 10:48 UTC, merged