Feat/res
json-schema-org/website pull request #509
Opened 2024-03-11 17:26 UTC by Akshaybagai52

**What kind of change does this PR introduce?**

**Issue Number:**

-  Closes #___ 
-  Related to #___ 
-  Others? 

**Screenshots/videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

2024-03-11 17:27 UTC, benjagm commented
What is the linked issue to this PR?

2024-03-11 17:32 UTC, Akshaybagai52 commented
> What is the linked issue to this PR?

https://github.com/json-schema-org/website/issues/282

2024-03-11 18:00 UTC, gregsdennis commented
@Akshaybagai52 please update the opening comment. The issue links you have are formatted oddly.  Just use the PR number, e.g. `#282`

2024-03-11 19:09 UTC, benjagm commented
There is still a lot of changes that are not required. Did you do a rebase?

2024-03-11 19:16 UTC, benjagm requested changes
This is looking really promising. 

You'll need to remove from this PR all the files unrelated to this feature. Have you rebased?

In addition: 

- I'll suggest reduce the space between every item of the list.
- Change the icon for the sidebar section of resources. Maybe something like this: https://icons.getbootstrap.com/icons/bookshelf/
- There is a strange effect when navigating that will require some attention. I'll record a video. This is the [video](https://github.com/json-schema-org/website/pull/509#issuecomment-1989253444).

2024-03-11 19:21 UTC, benjagm commented
The promised video with the strange behaviour when navigating between different resources and different sections of the sidebar.


https://github.com/json-schema-org/website/assets/40007659/ed337080-c16b-4630-b581-9300705aa093

2024-03-12 03:40 UTC, Akshaybagai52 commented on pages/resources/[slug].page.tsx
> +import React, { useEffect, useState } from 'react';
actually this is dynamic route so all the things depend on the value of slug which I'm getting from the route is it good to rename it to index file?

2024-03-12 04:41 UTC, Akshaybagai52 commented
> There is still a lot of changes that are not required. Did you do a rebase?

These changes are automatically coming whenever i'm changing base repo

2024-03-12 04:56 UTC, DhairyaMajmudar commented
I think its because you haven't synced the branch with the current branch.

2024-03-12 05:04 UTC, Akshaybagai52 commented
> I think its because you haven't synced the branch with the current branch.

Yeah I think I need to rebase the branch

2024-03-12 07:19 UTC, benjagm commented on pages/resources/[slug].page.tsx
> +import React, { useEffect, useState } from 'react';
> actually this is dynamic route so all the things depend on the value of slug which I'm getting from the route is it good to rename it to index file?

You are right. Let's leave this way thanks!

2024-03-13 11:56 UTC, benjagm commented
Thanks @Akshaybagai52 Please let me know when you need me to check this again.

2024-03-13 17:25 UTC, Akshaybagai52 commented
> Thanks @Akshaybagai52 Please let me know when you need me to check this again.

It is completed you can review now

2024-03-17 12:14 UTC, Akshaybagai52 commented
Hello @benjagm did you review this PR ?

2024-03-20 11:00 UTC, benjagm approved these changes
Amazing job here!! I pushed some changes to make sure it merges smoothly into the dev branch! Excellent Job!!

2024-03-20 11:02 UTC, merged

2024-03-20 12:53 UTC, Akshaybagai52 commented
> Amazing job here!! I pushed some changes to make sure it merges smoothly into the dev branch! Excellent Job!!

Thankyou ✨