Solved merge conflicts: Sidebar navigation
json-schema-org/website pull request #545
Opened 2024-03-15 13:44 UTC by VivekJaiswal18

**What kind of change does this PR introduce?**

**Issue Number:**

-  Closes #___ 
-  Related to #___ 
-  Others? 

**Screenshots/videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

2024-03-15 17:47 UTC, VivekJaiswal18 commented
Hey @benjagm please have a look into this.
Thank you!

2024-03-20 09:11 UTC, benjagm commented
This looks great!!! Can you please rebase to make sure there are no conflicts?

2024-03-20 09:11 UTC, benjagm requested changes
Looks great. Can you please rebase to make sure we don't have conflicts?

2024-03-20 12:29 UTC, VivekJaiswal18 commented
Thanks for the feedback @benjagm. Rebasing the commit

2024-03-23 18:29 UTC, VivekJaiswal18 commented
@benjagm rebased it please have a look.
Thank you

2024-03-24 06:44 UTC, DhairyaMajmudar commented on yarn.lock
> +
From here also : )

2024-03-24 07:42 UTC, VivekJaiswal18 commented
I think there is some issue with the command `yarn run format:fix` every time I run it, this adds unwanted changes in the code format especially in the global.css file. I think it needs to be addressed is there anyone else facing the same issue.
![image](https://github.com/json-schema-org/website/assets/96608169/300469db-027e-40e7-9677-fdce381cb0c6)
![image](https://github.com/json-schema-org/website/assets/96608169/3231b3fc-fbc9-4f39-8a6f-9bc1b502381a)

2024-03-24 07:56 UTC, JeelRajodiya commented
> I think there is some issue with the command `yarn run format:fix` every time I run it, this adds unwanted changes in the code format especially in the global.css file. I think it needs to be addressed is there anyone else facing the same issue. ![image](https://private-user-images.githubusercontent.com/96608169/316292785-3231b3fc-fbc9-4f39-8a6f-9bc1b502381a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyNjY3NTQsIm5iZiI6MTcxMTI2NjQ1NCwicGF0aCI6Ii85NjYwODE2OS8zMTYyOTI3ODUtMzIzMWIzZmMtZmJjOS00ZjM5LThhNmYtOWJjMWI1MDIzODFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI0VDA3NDczNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyMWEzOTc1YzMxZDBkZmY2NTJhNDZjNDdlZDYwZDI4NGQ3NDM2YzE5MjU1MTZlMDA3YWFkOTQ5MjE5OTQxMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VtdVA_O3eVj1NVQ-NNdLvMA3zLtTWqdJuFudsVN36qg)

I think it is normal, the global.css file was not following the rules defined in the prettier config. When you ran `format:fix` it ran prettier in that file as well 

It changed the tab width to 2 spaces.

2024-03-24 07:58 UTC, JeelRajodiya commented
I think you should keep it, so no one else has to tackle it in future.

2024-03-24 07:59 UTC, aialok commented
> I think there is some issue with the command `yarn run format:fix` every time I run it, this adds unwanted changes in the code format especially in the global.css file. I think it needs to be addressed is there anyone else facing the same issue.
> ![image](https://github.com/json-schema-org/website/assets/96608169/3231b3fc-fbc9-4f39-8a6f-9bc1b502381a)
> 
> 

I think the problem is coming because of this Prettier formatter options.

![Screenshot_20240324_132658_GitHub.jpg](https://github.com/json-schema-org/website/assets/66772290/09967f09-0b4d-4542-84cf-68ebcc00849f)

2024-03-24 08:31 UTC, VivekJaiswal18 commented
> > I think there is some issue with the command `yarn run format:fix` every time I run it, this adds unwanted changes in the code format especially in the global.css file. I think it needs to be addressed is there anyone else facing the same issue.
> > ![image](https://private-user-images.githubusercontent.com/96608169/316292785-3231b3fc-fbc9-4f39-8a6f-9bc1b502381a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyNjkzNDgsIm5iZiI6MTcxMTI2OTA0OCwicGF0aCI6Ii85NjYwODE2OS8zMTYyOTI3ODUtMzIzMWIzZmMtZmJjOS00ZjM5LThhNmYtOWJjMWI1MDIzODFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI0VDA4MzA0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4Y2ExYmU2NjQ2ZGU4MTM0ZjcyMjkwMDcwM2MyZjBkZGUyNzg4NDRhMGJhZjU4OTMzZjRkZmIzMzUzYzZiNzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HZww5sO5DJwciD96zn1Ifdi_AOSkaQmLkFZ8kt61LDA)
> 
> I think the problem is coming because of this Prettier formatter option.
> 
> ![Screenshot_20240324_132658_GitHub.jpg](https://private-user-images.githubusercontent.com/66772290/316293597-09967f09-0b4d-4542-84cf-68ebcc00849f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyNjkzNDgsIm5iZiI6MTcxMTI2OTA0OCwicGF0aCI6Ii82Njc3MjI5MC8zMTYyOTM1OTctMDk5NjdmMDktMGI0ZC00NTQyLTg0Y2YtNjhlYmNjMDA4NDlmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI0VDA4MzA0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhZDE0ZjhjN2Y3MmE3NTBlY2RhMTU2MjYzMmNlOTI0OTg1YjAzMzM5ZDBjOWI0N2MzMDU0NzJhYmRhMzMzYmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nulNMlir5TBMYiMdveiEGznzA2K0-lMNvdMUIic-KYk)

Yes you are correct beacause everyone is avoiding the these changes it is being carried on

2024-04-09 12:57 UTC, benjagm approved these changes
Great job! Thanks!!

2024-04-09 13:00 UTC, merged