First publication of the JSON Schema newsletter
json-schema-org/website pull request #628
Opened 2024-04-05 14:30 UTC by benjagm

**Summary**

This is the first edition of the JSON Schema newsletter.

2024-04-05 19:03 UTC, gregsdennis requested changes

2024-04-05 19:03 UTC, gregsdennis commented
We're adding this to the blog?  Is there a concern that newsletters will drown out other posts?

I think it makes sense to move newsletters and even case studies out to another page.  (Maybe we can discuss elsewhere.)

2024-04-05 19:06 UTC, benjagm commented on pages/blog/posts/newsletter-april-2024.md
> +* This month we discovered [Better AJV Errors](https://github.com/atlassian/better-ajv-errors) by the Atlassian Team. This tool improves the readability of the JSON Schema validation errors.
Thanks Greg. I'll remove it.

2024-04-05 19:09 UTC, benjagm commented
> We're adding this to the blog? Is there a concern that newsletters will drown out other posts?
> 
> I think it makes sense to move newsletters and even case studies out to another page. (Maybe we can discuss elsewhere.)

I agree 100%. In fact we already built the case studies page. I'll work on this next week.

Great idea! Thanks.

2024-04-08 21:50 UTC, benjagm commented
> I think it makes sense to move newsletters and even case studies out to another page. (Maybe we can discuss elsewhere.)

Great idea, I had been thinking about it but wasn't sure. Your comment helped to decide how to move newsletters out.
We'll do something similar to the CNCF weekly: https://www.cncf.io/kubeweekly/

This is the issue:
https://github.com/json-schema-org/website/issues/634

2024-04-11 16:54 UTC, radhesh1 commented
the logo needs to changed a bit it is not visible in dark mode

2024-04-23 08:43 UTC, closed without merging