Web release 3
json-schema-org/website pull request #655
Opened 2024-04-15 17:53 UTC by benjagm

This is the release 3 of the Documentation strategy containing:

  - [x] #421 
  - [x] #190 
  - [x] #280
  - [x] #282 
  - [x] #426 
  - [x] #243 
  - [x] #440

2024-05-20 10:18 UTC, benjagm commented
@DhairyaMajmudar can you continue with the work of this PR?

2024-05-20 11:21 UTC, DhairyaMajmudar commented
Sure thing looking forward to continue the work on this :D

2024-05-29 07:50 UTC, aialok commented on components/Card.tsx
> +        {image && <img src={image} className='h-32 p-2' />}
I think it is better to use Next.js prebuilt `Image` Component. It does some optimization under the hood.

https://nextjs.org/learn-pages-router/seo/improve/images
https://nextjs.org/docs/pages/building-your-application/optimizing/images

2024-05-29 07:51 UTC, aialok commented on components/Card.tsx
> +            <img src={icon} alt={title} className='h-full w-full' />
Better to use Next.js prebuilt Image Component.

2024-05-29 07:51 UTC, aialok commented on components/DarkModeToggle.tsx
>        <img src={img} alt='Dark Mode' width={25} height={25} />
Better to use Next.js prebuilt Image Component.

2024-05-30 09:30 UTC, benjagm commented
Note for reviewers: 

The review we are expecting from this PR is just the content, the technical part has been reviewed with the referenced PRs.

2024-05-30 14:50 UTC, Relequestual requested changes
Overall, this is huge progress and represents a great step forward in making JSON Schema more presentable to first time users and those with a vague passing familiarity. Thank you to everyone involved!

I've left a number of suggestions for changes, and a number of questions and comments.
I do think some work is needed before this should go live, but most of it is minor.

2024-05-30 14:50 UTC, Relequestual commented on pages/overview/what-is-jsonschema.md
> +* **Enhancing Data Documentation**: JSON Schema enables the creation of clear and standardized representations of data. This improves understanding and collaboration among developers, stakeholders, a
```suggestion
* **Enhancing Data Documentation**: JSON Schema enables the creation of clear and standardized representations of data structures. This improves understanding and collaboration among developers, stakeholders, and collaborators, enhancing organizational efficiency.
```

2024-05-30 14:50 UTC, Relequestual commented on pages/overview/what-is-jsonschema.md
Overall the changes / updates here are great. Nice work!

2024-05-30 14:50 UTC, Relequestual commented on data/community.json
How will this data be updated / maintained?

2024-05-30 14:50 UTC, Relequestual commented on data/welcome.json
This feels a little overkill.
I think this data can be directly included in the file for the page rather than as its own file.

2024-05-30 14:50 UTC, Relequestual commented on data/case-studies.json
Where will the canonical source of this data be kept?

2024-05-30 15:41 UTC, DhairyaMajmudar commented on .github/workflows/greet_on_first_merge.yml
This workflow is moved and consolidated in a single workflow file

cc: @aialok

2024-06-01 15:14 UTC, DhairyaMajmudar commented on pages/community/index.page.tsx
> +import axios from 'axios';
Done with this 👍🏻

2024-06-01 15:22 UTC, DhairyaMajmudar commented
We are still facing bugs related to width in the FAQ section which can be fixed if we add one more line in the paragraph below

![image](https://github.com/json-schema-org/website/assets/124715224/74013a02-1224-4389-ac3a-4c81a2c108f8)

2024-06-02 17:55 UTC, benjagm commented on styles/globals.css
> +}
There is logic in the community page that is dynamically using numbers to build the styles of the events table.

2024-06-06 08:16 UTC, Relequestual commented on .github/workflows/greet_on_first_merge.yml
OK, looks like the file vanished after merging main.

2024-06-06 08:19 UTC, Relequestual commented on public/img/event/meet.png
No, I mean, this file name doesn't appear anywhere else. Do we actually need this file or can it be deleted?

2024-06-06 08:24 UTC, Relequestual commented on styles/globals.css
> +}
OK

2024-06-06 08:26 UTC, Relequestual commented on data/community.json
Great. Can you open an Issue for this please? Then I'm happy to resolve the comment.

2024-06-06 08:30 UTC, Relequestual commented on data/case-studies.json
Sorry, I mean, will this file be the source of truth? If so, let's make sure we document this fact.
In fact, it would be good to have a markdown file in the data folder which explains what each file represents and if it is the source of truth.

2024-06-06 08:46 UTC, benjagm commented on data/case-studies.json
Thanks Ben. We'll cover this in a new issue as soon this is merged.

2024-06-06 08:47 UTC, benjagm commented on components/Faq.tsx
Thanks Ben. We'll leave it for now and revisit for future releases.

2024-07-24 07:03 UTC, merged