Change format positioning to be under type instead of string, More cl…
json-schema-org/website pull request #664
Opened 2024-04-18 12:12 UTC by bhavukkalra

**What kind of change does this PR introduce?**
PR moves the `format` section of the documentation from the misplaced [string](https://json-schema.org/understanding-json-schema/reference/string) page to under the more generic [type](https://json-schema.org/understanding-json-schema/reference/type) as discussed in [Issue #759](https://github.com/json-schema-org/json-schema-spec/issues/759). Which aims to remove the Misinterpretation that the reader might get that `format` as a keyword is only for string types which is not the case.

Also, Add further clarification that `format` as a keyword is generic. Using these lines added further

![image](https://github.com/json-schema-org/website/assets/41142068/68f5306c-b5e5-492b-ac94-411c80672b6f)

**Issue Number:**
-  Closes #187 

**Screenshots**

- Added section under [type](https://json-schema.org/understanding-json-schema/reference/type) page

![image](https://github.com/json-schema-org/website/assets/41142068/35c540d1-5647-4ec4-872b-9c200275571f)

- removed from `format` section from [string](https://json-schema.org/understanding-json-schema/reference/string) page

![image](https://github.com/json-schema-org/website/assets/41142068/d221a03f-31f1-4e26-a27d-032202a07123)

**Summary**
PR aims to re-adjust the positioning of `format` keyword definitions. To remove any confusion of it being a `string` specific keyword as reported by the users here [Slack Archives](https://json-schema.slack.com/archives/C5CF75URH/p1562596499404200)

**Does this PR introduce a breaking change?**
No

2024-04-23 08:37 UTC, benjagm commented
> misplaced [string](https://json-schema.org/understanding-json-schema/reference/string) page to under the more generic [type](https://json-schema.org/understanding-json-schema/reference/type) as discussed in https://github.com/json-schema-org/json-schema-spec/issues/759

I checked the issue https://github.com/json-schema-org/json-schema-spec/issues/759 and it was closed 2019. Are you sure you are referring to the right issue?

2024-04-30 12:05 UTC, benjagm approved these changes
Great work Bhavuk, Thanks!!

2024-05-04 06:46 UTC, kakabisht commented on pages/understanding-json-schema/reference/type.md
> +kinds of values that are commonly used. or user could define its own format and use them alongside
Nitpicking: A typo + not in present tense
Suggestion: kinds of commonly used, or a user could define their format and use them alongside

2024-05-04 06:51 UTC, kakabisht commented on pages/understanding-json-schema/reference/type.md
> +annotation. That means that validation will fail if, for example, a
Nitpick :
Suggestion: validation fails when, for example a value with date format.

2024-05-04 06:53 UTC, kakabisht commented on pages/understanding-json-schema/reference/type.md
> +date. This can allow values to be constrained beyond what the other
Suggestion:
This allows values to be constrained beyond what the other tools in JSON Schema can do, including Regular Expressions.

2024-05-04 06:55 UTC, kakabisht commented on pages/understanding-json-schema/reference/type.md
> +However, custom formats may also be used, as long as the parties
Suggestion: 
However, custom formats may also be used if the parties exchanging the JSON documents share information about the custom format types

2024-05-04 06:58 UTC, kakabisht commented on pages/understanding-json-schema/reference/type.md
> +- `"time"`: <StarInline label="New in draft 7" /> Time, for example, `20:20:39+00:00`
```suggestion
- `"time"`: <StarInline label="New in draft 7" /> Time, for example, `20:20:39+00:00`. 
```

2024-05-04 06:59 UTC, kakabisht commented on pages/understanding-json-schema/reference/type.md
> +However, custom formats may also be used, as long as the parties
Suggestion: 
However, custom formats may also be used if the parties exchanging the JSON documents share information about the custom format types

2024-05-04 07:04 UTC, kakabisht commented on pages/understanding-json-schema/reference/type.md
> +  discussion on the use of JSON Pointer within JSON Schema in
```suggestion
  discussion on using JSON Pointer within JSON Schema in
```

2024-05-04 07:05 UTC, kakabisht commented on pages/understanding-json-schema/reference/type.md
> +- `"regex"`: <StarInline label="New in draft 7" /> A regular expression, which should be valid according to
```suggestion
- `"regex"`: <StarInline label="New in draft 7" /> A regular expression that should be valid according to
```

2024-05-04 07:06 UTC, kakabisht commented
Hello, 
I followed the Microsoft style guide for technical writing to review the content. 
My only concern is formatting the code snippets. If you are fixing the code snippet indentation here, It would help if you also fixed the indentation across the entire documentation.

2024-05-21 09:16 UTC, gregsdennis commented on pages/understanding-json-schema/reference/type.md
> +kinds of values that are commonly used. or user could define its own format and use them alongside
Grammatically, this still seems incomplete.

As written:

> The `format` keyword allows for basic semantic identification of certain
kinds of values that are commonly used. or user could define its own format and use them alongside

- "... commonly used. or user could ..." - The second sentence seems to start in the middle of a thought.
- "and use them alongside" - Alongside what?  This needs an object.

As suggested:

> The `format` keyword allows for basic semantic identification of certain kinds of commonly used, or a user could define their format and use them alongside

- "certain kinds of commonly used..." - Commonly used what?  Object needed.
- "and use them alongside" - Alongside what?  This needs an object.

---

My suggestion:

> The `format` keyword conveys semantic information for values that may be difficult or impossible to describe using JSON Schema. Typically, this semantic information is described by other documents. The JSON Schema Validation specification defines a number of formats, however  this keyword also allows schema authors to define their own formats.

2024-05-21 09:17 UTC, gregsdennis requested changes
@bhavukkalra please address the outstanding comments.  We can merge afterward.

2024-07-24 07:05 UTC, benjagm commented
This issue is going to be closed due to inactivity.

2024-07-24 07:05 UTC, closed without merging