I Updated the base URI and included a Draft-specific info box section
json-schema-org/website pull request #673
Opened 2024-04-22 17:16 UTC by Dule-martins

`$ids` were changed to absolute URIs. A Draft-specific Info block that supports changing dialects in an embedded schema (using $schema with a different value than the parent schema) with an explanation of the difference between 2020-09 and 2020-12

**What kind of change does this PR introduce?**
refactoring doc

**Issue Number:**

-  Closes #647  
 
 

**Screenshots/videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

2024-04-24 10:44 UTC, Dule-martins commented on pages/understanding-json-schema/structuring.md
> +   all other fragments in $id had undefined behavior previously.
Yes, I thought of adding it because I was trying to show the difference between Draft 2020-12 and 2020-9, but I can remove it @jdesrosiers

2024-05-01 13:52 UTC, jdesrosiers commented on pages/understanding-json-schema/structuring.md
> +   all other fragments in $id had undefined behavior previously.
Yes, please remove it

2024-05-16 12:32 UTC, benjagm commented
Hi @Dule-martins . We are almost done with the changes to merge this PR. Can you please review the last comments?

2024-05-16 17:14 UTC, Dule-martins commented
I will do that later tonight, after work thank you
On Thu, 16 May 2024 at 13:33, Benjamin Granados ***@***.***>
wrote:

> Hi @Dule-martins <https://github.com/Dule-martins> . We are almost done
> with the changes to merge this PR. Can you please review the last comments?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/json-schema-org/website/pull/673#issuecomment-2115129985>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AH4ASUU3GMHYXK2KZUWJUGDZCSRQHAVCNFSM6AAAAABGTF7LU2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCMJVGEZDSOJYGU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-06-25 14:55 UTC, Dule-martins commented
> Hi @Dule-martins . We are almost done with the changes to merge this PR. Can you please review the last comments?

Hey @benjagm my apologies it took me longer than I thought before returning to this PR! 
 I removed the two lines of sentences that were highlighted by @jdesrosiers

2024-06-25 23:16 UTC, jdesrosiers requested changes

2024-06-25 23:16 UTC, jdesrosiers commented on pages/understanding-json-schema/structuring.md
> +   (using $schema with a different value than the parent schema) was added.
The way `$id` is used here confuses me. I think it makes more sense just to drop it.

```suggestion
In Draft 2020-12, support for changing dialects in an embedded schema 
   (using `$schema` with a different value than the parent schema) was added.   
```

2024-06-26 17:46 UTC, jdesrosiers approved these changes

2024-06-26 17:46 UTC, merged

2024-06-26 17:47 UTC, jdesrosiers commented
Thanks for making this happen :clap:

2024-06-26 18:03 UTC, Dule-martins commented
> Thanks for making this happen 👏

Your guidance saw me through. Thanks and would love to more if possible