Update index.page.tsx
json-schema-org/website pull request #684
Opened 2024-04-30 15:14 UTC by kwennB

What kind of change does this PR introduce?
Enhancement to documentation

Issue Number:
Closes [660](https://github.com/json-schema-org/website/issues/660)

Summary
Removed the placeholders texts for the newly created welcome page in the release 3.
[json-schema-org#660](https://github.com/json-schema-org/website/issues/660)

Does this PR introduce a breaking change?
No

2024-05-07 15:23 UTC, DhairyaMajmudar reviewed
Hello, @kwennB can you pls. once have a look at that failing lint check.

Thank You : )

2024-05-10 14:52 UTC, DhairyaMajmudar approved these changes

2024-05-21 08:28 UTC, benjagm requested changes
Hi @kwennB . Nice job!

As discussed please adjust the tone to better fit our personas.

2024-05-23 11:00 UTC, benjagm requested changes
I just left small suggestions before getting this merged.

2024-05-23 11:00 UTC, benjagm commented on pages/overview/welcome/index.page.tsx
> +        JSON data.
```suggestion
        Discover everything you can do with JSON Schema. This section presents
        the most common use cases for JSON Schema, but the possibilities are
        endless.
```

2024-05-23 11:00 UTC, benjagm commented on pages/overview/welcome/index.page.tsx
> +        'Explore our different resources, books, articles, courses, videos, podcasts, and papers, we welcome you to enjoy them.',
```suggestion
        'Deserunt et fugiat do adipisicing enim in nostrud Lorem anim ut amet enim.',
```

Please don't modify the resources description. That section is going to be removed from release 3.

2024-05-23 12:20 UTC, benjagm approved these changes
Nice job Blessing!

2024-05-23 12:44 UTC, merged