Feature : github-actions - Setup stale Issues and PRs workflow
json-schema-org/website pull request #690
Opened 2024-05-17 10:06 UTC by aialok

**What kind of change does this PR introduce?**
- This PR will setup workflow to manage stale issues and pull-request. 

**Issue Number:**

-  Closes #689 

**Screenshots/videos:**

**If relevant, did you update the documentation?**

**Summary**
This feature involves setting up a workflow to manage stale issues and pull requests (PRs) effectively. Stale issues and PRs can accumulate over time, leading to clutter and reduced productivity. By implementing this workflow, we aim to automatically identify and label stale issues and PRs based on predefined criteria. Additionally, the workflow will incorporate actions such as notifying contributors, closing stale items, or prompting for updates to keep the issue tracker organized and relevant. This feature will streamline issue and PR management, ensuring that active contributions receive timely attention while maintaining a clean and responsive development environment.

**Does this PR introduce a breaking change?**

- No

2024-05-21 08:51 UTC, benjagm requested changes
Great job Alok. I just left some suggestions.

2024-05-21 08:51 UTC, benjagm commented on .github/workflows/stale.yml
> +        days-before-stale: 14
```suggestion
        days-before-stale: 30
```

Let's move it to 30 days.

2024-05-21 08:51 UTC, benjagm commented on .github/workflows/stale.yml
> +        stale-issue-label: 'no-issue-activity'
```suggestion
        stale-issue-label: 'Status: Stale'
```

2024-05-21 08:51 UTC, benjagm commented on .github/workflows/stale.yml
> +        stale-pr-label: 'no-pr-activity'
```suggestion
        stale-pr-label: 'Status: Stale'
```

2024-05-24 06:41 UTC, aialok commented
Done with the requested changes.
Thank you  : )

2024-05-27 12:39 UTC, benjagm requested changes
I left a small comment to change the trigger periodicity to weekly instead daily.

2024-05-27 12:39 UTC, benjagm commented on .github/workflows/stale.yml
> +  - cron: "0 0 * * *" # Every day at 00:00 UTC
I think weekly is enough.

2024-05-27 15:10 UTC, aialok commented
I made the requested changes. One test is going to fail authorized file detection one as the changes in the workflow file.

2024-05-28 08:16 UTC, benjagm approved these changes
Looks good. Thanks Alok.

2024-05-28 09:54 UTC, benjagm approved these changes
Good job Alok!

2024-05-28 09:58 UTC, merged