improved FAQ description text
json-schema-org/website pull request #709
Opened 2024-05-24 12:35 UTC by kwennB

**What kind of change does this PR introduce?**

Documentation Enhancement

**Issue Number:**

-  Closes #___  [706](https://github.com/json-schema-org/website/issues/706)

-  Others? 
I also reviewed the general question texts, which are properly formatted and good to go.

**Does this PR introduce a breaking change?**

No

2024-05-25 04:19 UTC, DhairyaMajmudar reviewed
Here pls. add one more sentence in this paragraph since there's a bug related to faq page width which is fixed by width of two-liner paragraph.

2024-05-25 08:41 UTC, kwennB commented
> Here pls. add one more sentence in this paragraph since there's a bug related to faq page width which is fixed by width of two-liner paragraph.

Alright, I'll update this.

2024-05-25 09:20 UTC, benjagm requested changes
The description looks good, however to close this issue we need to review the wording and completeness of each question and answer. 

The data fetched for the questions is available in the file:
/data/faq.json

2024-05-25 09:27 UTC, kwennB commented
> The description looks good, however to close this issue we need to review the wording and completeness of each question and answer.
> 
> The data fetched for the questions is available in the file: /data/faq.json

Noted, thank you.

2024-05-28 08:30 UTC, benjagm requested changes
Great work Blessing!! I just left some suggestions.

2024-05-28 08:30 UTC, benjagm commented on data/faq.json
> +    "answer": "JSON Schema is a specification for defining the structure of JSON data. It provides a standardized way to annotate, describe, and validate JSON data. JSON Schema defines content, struc
```suggestion
    "answer": "JSON Schema is a specification for defining the structure of JSON data. It provides a standardized way to annotate, describe, and validate JSON data. JSON Schema defines content, structure, data types, and other expected constraints within a JSON document.",
```

2024-05-28 08:30 UTC, benjagm commented on data/faq.json
> +    "answer": "You create a simple JSON Schema by defining keywords such as 'schema', 'id', 'title', 'description', and 'type', which specify the version, unique identifier, title, and, description o
```suggestion
    "answer": "You can create a simple JSON Schema using a JSON object with properties like 'type', 'properties', and 'required'. These define the data type, properties, and mandatory fields of your JSON document.",
```

Let's keep this one simple.

2024-05-28 08:30 UTC, benjagm commented on data/faq.json
> +    "answer": "You can define default values for properties using the 'default' keyword, which provides a fallback value if the property is not present in the JSON document. This feature is useful fo
```suggestion
    "answer": "You can use the 'default' keyword to set a default value for a property in your JSON Schema. It provides a fallback value if the property is not present in the JSON document.",
```

2024-05-28 09:44 UTC, benjagm approved these changes
Great work!

2024-05-28 09:44 UTC, benjagm commented on pages/overview/faq/index.page.tsx
> +        we get asked the most about JSON Schema.
```suggestion
        Below you'll find answers to questions we get asked the most about JSON Schema.
```

2024-05-28 09:49 UTC, merged