New spec structure
json-schema-org/website pull request #819
Opened 2024-07-23 10:01 UTC by kwennB

**What kind of change does this PR introduce?**

Documentation Enhancement
![image](https://github.com/user-attachments/assets/f27b8bb0-ef58-4de3-b697-fd730ce14798)

**Issue Number:**

- Closes #___ [[📝 Docs]: Implement the Spec restructuring (Docs Website) #791](https://github.com/json-schema-org/website/issues/791)

**Screenshots/videos:**

Added

**Summary**

The Specification section of the docs is fixed to adapt to the proposed change in alignment with Diataxsis and issue #791

- It fixes the spec navigation
- Draft templates
- Re-edits Release note page
- Re-edits JSON hyper-schema page
- Adds a Migration page

**Does this PR introduce a breaking change?**

No

2024-07-23 22:19 UTC, gregsdennis submitted a review, later dismissed
Please see my comment in the associated issue.  I don't feel we should be reformatting these documents. 

Blocking until that is resolved.

2024-07-23 22:22 UTC, benjagm commented
> Please see my comment in the associated issue. I don't feel we should be reformatting these documents.

Let's discuss this Greg. I asked the docs team to do this. I have strong arguments for this change.

2024-07-23 22:23 UTC, gregsdennis commented
I agree it needs to be discussed. It never was. We should use the issue.

2024-07-23 22:33 UTC, benjagm commented
This is part of the Google Season of Docs projects and the issue has been there for months.

My feeling is you think we are republishing, and we are just reorganizing and elevating our docs.

If you think we shouldn't add the draft publication details like authors in this page that is fine. We can change that and other things as per the community feedback.

 We are going to reestructure the website docs....that is what the Docs strategy issue is about and why we applied to GSoD.

2024-07-24 06:38 UTC, benjagm requested changes
Hi Blessing. Great work wit this first PR. 

I left some comments. Migration, JSON Hyper Schema and release notes need still a lot of work.

2024-07-24 06:38 UTC, benjagm commented on pages/draft/2020-12/index.md
> +### Access all data connected to Draft 2020-12
I suggest calling this section just "Draft 2020-12 Documents"

2024-07-24 06:38 UTC, benjagm commented on components/DocTable.tsx
> +                Specification
```suggestion
                **Specification**
```

Let's make bold each property name.

2024-07-24 06:38 UTC, benjagm commented on components/Sidebar.tsx
Please check the getSpecificationPath property. You should add all the paths here, otherwise the sidebar is not going to work properly.

2024-07-24 06:38 UTC, benjagm commented on pages/format4/index.page.tsx
Please remove format4 folder completely. Right?

2024-07-24 06:38 UTC, benjagm commented on pages/migration/index.md
This page needs more work. We should call out here Alterschema https://github.com/sourcemeta/alterschema as the tool to help with the migration to newer schemas. Please speak with @jviotti (TSC member). He is probably the best person the speak with to create here a new great page.

Check examples in other languages like:  https://www.asyncapi.com/docs/migration/migrating-to-v3

2024-07-24 06:38 UTC, benjagm commented on pages/json-hyper-schema/index.page.tsx
This page requires work as well. I think it requires an introduction, all the links and finally the release notes.

We should update the sidebar to add all the child pages.

2024-07-24 06:38 UTC, benjagm commented on pages/release-note/index.page.tsx
> +import React from 'react';
Folder name should be `release-notes`

2024-07-24 06:38 UTC, benjagm commented on pages/release-note/index.page.tsx
> +export async function getStaticProps() {
This pages needs a lot of work. I'll try to push some code later today.

2024-07-24 06:38 UTC, benjagm commented on components/DocTable.tsx
> +import React from 'react';
Can we refine the style of the table to be similar to this one  (@DhairyaMajmudar )

https://developer.android.com/about/versions/15/release-notes?hl=es-419

2024-07-24 09:44 UTC, kwennB commented on pages/format4/index.page.tsx
Yes.

2024-07-24 09:49 UTC, kwennB commented on pages/json-hyper-schema/index.page.tsx
The JSON-hyper-schema page cannot carry all the release notes. What would be the usefulness of the release notes page?

I agree with having an introduction and updating the sidebar to carry all child pages. When you say 'all the links' - all the hyper-schema links, yes?

2024-07-24 09:57 UTC, kwennB commented on components/Sidebar.tsx
That is correct, will do.

2024-07-24 11:58 UTC, kwennB commented on pages/draft-06/index.md
> +Implementations: 'https://bowtie.report/#/dialects/draft2020-12'
Noted.

2024-07-24 17:40 UTC, closed without merging