feat: adding keywords page
json-schema-org/website pull request #844
Opened 2024-08-04 06:59 UTC by DhairyaMajmudar

**What kind of change does this PR introduce?**

Adding new keywords page

**Issue Number:**

-  Closes #815

**Screenshots/videos:**
![image](https://github.com/user-attachments/assets/2152d53b-d53c-4cd4-a761-cf12d6fd533b)

**If relevant, did you update the documentation?**
N/A

**Summary**

A new keywords page is added.

2024-08-05 10:52 UTC, benjagm requested changes
Great first version! Congrats. I left some comments to make some adjustments but we are very close!

2024-08-05 10:52 UTC, benjagm commented on data/keywords.yml
> +- title: JSON Schema Keywords
We dont need title of the page and description here ... it does not make sense. This file is only for keywords.

2024-08-05 10:52 UTC, benjagm commented on data/keywords.yml
> +  categorys:
We need to change the structure to store URLs and titles of the URLs and also allow 1 keyword to belong to multiple vocabularies without having to duplicate it. Find below an example :

````
- name: $anchor
  vocabulary: [core]
  links:
    - url: 'https://json-schema.org/learn/json-schema-examples#ecommerce-system'
      title:
    - url: 'https://json-schema.org/understanding-json-schema/structuring#anchor'
      title:
    - url: 'https://www.learnjsonschema.com/2020-12/core/anchor'
      title:
- name: $comment
  vocabulary: [core]
  links:
    - url: 'https://json-schema.org/understanding-json-schema/reference/comments#comments'
      title:
    - url: 'https://www.learnjsonschema.com/2020-12/core/comment'
      title:
- name: $defs
  vocabulary: [core]
  links:
    - url: 'https://json-schema.org/learn/miscellaneous-examples'
      title:
    - url: 'https://json-schema.org/understanding-json-schema/structuring#defs'
      title:
    - url: 'https://www.learnjsonschema.com/2020-12/core/defs'
      title:
- name: $dynamicAnchor
  vocabulary: [core]
  links:
    - url: 'https://www.learnjsonschema.com/2020-12/core/dynamicanchor'
      title:
- name: $dynamicRef
  vocabulary: [core]
  links:
    - url: 'https://www.learnjsonschema.com/2020-12/core/dynamicref'
      title:
- name: $id
  vocabulary: [core]
  links:
    - url: 'https://json-schema.org/learn/getting-started-step-by-step#create-a-schema-definition'
      title:
    - url: 'https://json-schema.org/understanding-json-schema/basics#declaring-a-unique-identifier'
      title:
    - url: 'https://www.learnjsonschema.com/2020-12/core/id'
      title:
- name: $ref
  vocabulary: [core]
  links:
    - url: 'https://json-schema.org/learn/getting-started-step-by-step#create-a-schema-definition'
      title:
    - url: 'https://json-schema.org/understanding-json-schema/basics#declaring-a-json-schema'
      title:
    - url: 'https://json-schema.org/understanding-json-schema/reference/array#unevaluateditems'
      title:
    - url: 'https://json-schema.org/understanding-json-schema/structuring#id'
      title:
    - url: 'https://www.learnjsonschema.com/2020-12/core/ref'
      title:
- name: $schema
  vocabulary: [core]
  links:
    - url: 'https://json-schema.org/understanding-json-schema/reference/schema'
      title:
    - url: 'https://www.learnjsonschema.com/2020-12/core/schema'
      title:
````

2024-08-05 10:52 UTC, benjagm commented on pages/keywords/index.page.tsx
> +import React from 'react';
Some comments:

- keywords should be shorted alphabetically without any grouping (vocabulary is only a property)
- Avoid using a table. I provided an example using an unsorted list (bullet points). Plese check the issue
- For the links we should store links and titles. Please show the titles and create links with the URLs to provide a most friendly approach for showing urls.

2024-08-19 13:45 UTC, benjagm approved these changes
Looks great! Amazing job @DhairyaMajmudar !

2024-08-19 17:52 UTC, jdesrosiers approved these changes
This looks like a really useful resource!

I do worry about it getting out of date as the website evolves. Is there a checklist for adding things the to website? Having something that reminds to check if this index needs to be updated would be a good idea.

2024-08-21 08:15 UTC, merged