Web feat diataxis
json-schema-org/website pull request #955
Opened 2024-09-19 06:04 UTC by benjagm

**What kind of change does this PR introduce?**

**Issue Number:**

-  Closes #___ 
-  Related to #___ 
-  Others? 

**Screenshots/videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

2024-09-19 23:33 UTC, kwennB reviewed
Review added, thank you.

2024-09-19 23:33 UTC, kwennB commented on components/NextPrevButton.tsx
I got to the end of each document and could not find the Next/Prev in action. Am I missing something?

![image](https://github.com/user-attachments/assets/a3a03016-9ba1-411e-84da-12f74e200cb7)

2024-09-19 23:33 UTC, kwennB commented on pages/draft-06/json-hyper-schema-release-notes.md
I am pointing out that the Hyperschema is still on the same page as the draft releases; considering that we will be creating a dedicated page for Hyperschema, would it not be redundant to keep it here?

2024-09-19 23:33 UTC, kwennB commented on pages/draft-07/json-hyper-schema-release-notes.md
The Hyoerschema is also on the same page with the Draft release.

2024-09-20 04:10 UTC, benjagm commented on components/NextPrevButton.tsx
I am not adding it as it will require it to be added to the whole site and it will require lots of work. At the moment I am just adding the component to the code base.

2024-09-20 04:13 UTC, benjagm commented on pages/draft-07/json-hyper-schema-release-notes.md
can you elaborate a bit more to make sure I understand what you do mind and what is the change/action you are suggesting?

2024-09-20 04:18 UTC, benjagm commented on pages/draft-06/json-hyper-schema-release-notes.md
I just reviewed and refined what you had previously in your PR: https://github.com/json-schema-org/website/pull/823

My understanding is you/we decided to release an MVP version of the Hyperschema page as it is to later go with the new page you are working on. As soon as you have that new page we can better understand what changes need to be made and what files need to be moved.

2024-09-20 04:18 UTC, benjagm commented on pages/draft-07/json-hyper-schema-release-notes.md
I just reviewed and refined what you had previously in your PR: https://github.com/json-schema-org/website/pull/823

My understanding is you/we decided to release an MVP version of the Hyperschema page as it is to later go with the new page you are working on. As soon as you have that new page we can better understand what changes need to be made and what files need to be moved.

2024-09-20 08:54 UTC, kwennB commented on pages/draft-06/json-hyper-schema-release-notes.md
Yes you're right and that works.

2024-09-20 08:54 UTC, kwennB commented on pages/draft-07/json-hyper-schema-release-notes.md
Yes you're right and that works as well

2024-09-23 15:57 UTC, valeriahhdez commented
LGTM

2024-09-24 07:04 UTC, kwennB approved these changes
It's all good now.

2024-09-24 14:10 UTC, DarhkVoyd requested changes
Most of the changes are docs related so I just skimmed over the changes, on the technical side I left a comment.

2024-09-24 14:10 UTC, DarhkVoyd commented on public/_redirects
The headline fragment identifiers `#` won't work in redirects because they are a browser construct and not available to the server.

2024-09-24 14:18 UTC, benjagm commented on public/_redirects
Thanks DV. We are using fragments just for target urls and in that case it works.

Regarding the new structure of the spec section,what do you think compared with the previous?

2024-09-24 14:40 UTC, DarhkVoyd commented on public/_redirects
I missed that, my bad. You are right. Overall, I like the new structure, it feels more friendly to a new adapter. The addition of migration to sidebar is great. 

On the release notes page cards, in my opinion, it would be better to have truncated/summarised content instead of `Draft 2020-12 release notes` twice, on hover it shows `read more` so I think that's what should happen,

2024-10-02 08:11 UTC, merged

2024-10-06 21:33 UTC, Julian commented
Do we have a policy on preserving links / adding redirects when we change something? Specifically I think this PR broke a few -- I notice because my CI (on `python-jsonschema`) has begun to fail. A specific example is https://json-schema.org/draft/2019-09/release-notes.html#format-vocabulary which used to resolve and is now a 404.

I'm going to update my links to unbreak CI on my side but just flagging in case this wasn't intentional.

2024-10-06 21:36 UTC, Julian commented
More specifically, two things seem to have changed in that specific example, judging from the new link, which seems to be:

https://json-schema.org/draft/2019-09#format-vocabulary

That looks quite unintentional -- specifically the new URL for release notes seems to be https://json-schema.org/draft/2019-09#draft-2019-09-release-notes, and the new fragment for the format vocabulary changes within the release notes seems to be https://json-schema.org/draft/2019-09#format-vocabulary where the fragment is no longer even inside `release-notes` / indicates that this is release note related.

2024-10-07 05:19 UTC, benjagm commented
Sorry for the situation @Julian . We created some redirects that should have avoided the 404, but for any reason they are not working as expected. This added to your comment regarding the URL structure makes me think about reverting the change and coming back to the previous release notes structure. I am planning to have this done later today

2024-10-09 04:28 UTC, benjagm commented
Hi everyone! Thanks a lot for helping us find the problems created by the changes in the release notes. This PR fixes all making the all release notes accessible again:

https://github.com/json-schema-org/website/pull/1010