Enhancement: Replace <img> tags with Next.js Image Component #824
json-schema-org/website pull request #997
Opened 2024-10-03 13:55 UTC by 29deepanshutyagi

This PR refactors several <img> tags throughout the project to utilize the <Image> component provided by Next.js. Replaced <img> tags with <Image> components 
added the error level to the ESLint configuration for img tag to enforce stricter code quality.

changes are pushed through check branch

issue #824

2024-10-04 07:09 UTC, benjagm requested changes
Thanks a lot for this PR!! Nice job. I just left small comments.

2024-10-04 08:51 UTC, 29deepanshutyagi commented on components/GettingStarted.tsx
> +                className='p-2 border dark:border-slate-300 border-slate-800 dark:bg-slate-900 rounded-md max-sm:text-[12px] plausible-event-name==activation-explore-tools'
Sure

2024-10-04 15:03 UTC, 29deepanshutyagi commented
@benjagm  all requested changes are done ,kindly check

2024-10-06 02:17 UTC, DarhkVoyd requested changes

2024-10-06 02:17 UTC, DarhkVoyd commented on pages/tools/index.page.tsx
These changes break the CTA styles.

2024-10-06 02:25 UTC, DarhkVoyd requested changes

2024-10-06 02:25 UTC, DarhkVoyd commented on pages/index.page.tsx
Some of these changes introduces hydration errors on the homepage, kindly check the dev console.

2024-10-06 07:28 UTC, 29deepanshutyagi commented on pages/tools/index.page.tsx
can you kindly ellaborate,if possible

2024-10-18 16:25 UTC, DhairyaMajmudar commented on components/Card.tsx
> +            width={128} // Corresponds to h-32 (128px)
please remove this extra commnets

2024-10-18 16:30 UTC, DhairyaMajmudar commented on components/Card.tsx
> +              height={56} // Corresponds to h-14 (56px)
Please remove extra comments

2024-10-18 16:30 UTC, DhairyaMajmudar commented on components/GettingStarted.tsx
> +              />
Pls. remove extra comments

2024-10-18 16:32 UTC, DhairyaMajmudar commented on components/Layout.tsx
> +          alt={''}
Fill in the proper alt title

2024-10-18 16:32 UTC, DhairyaMajmudar commented on components/StyledMarkdown.tsx
> +                      alt={''}
Fill in  the proper alt title

2024-10-18 16:37 UTC, 29deepanshutyagi commented on components/StyledMarkdown.tsx
> +                      alt={''}
sure

2024-10-18 17:07 UTC, DhairyaMajmudar reviewed
@29deepanshutyagi left some suggestions to be added in the PR

2024-10-18 17:07 UTC, DhairyaMajmudar commented on pages/blog/posts/[slug].page.tsx
> +                  />
```suggestion
                    width={16} // Corresponds to 'w-4' in Tailwind (4 * 4 = 16px)
                    height={16}
                    className='h-4 w-4 mr-2'
                    alt='Left arrow icon'
                  />
```

2024-10-18 17:07 UTC, DhairyaMajmudar commented on pages/community/index.page.tsx
> +                    alt={''}
Add meaningful alt text here

2024-10-18 17:07 UTC, DhairyaMajmudar commented on pages/index.page.tsx
> +                {isClient && (
Please remove the conditional rendering of the image and add meaningful alt texts

2024-10-18 17:07 UTC, DhairyaMajmudar commented on pages/index.page.tsx
> +          )}
Remove conditional rendering of image and add meaningful alt text

2024-10-18 17:07 UTC, DhairyaMajmudar commented on pages/index.page.tsx
> +
No need of this, pls. remove it and conditionally rendered images

2024-10-18 17:07 UTC, DhairyaMajmudar commented on pages/tools/components/ToolingDetailModal.tsx
> +                alt={''}
```suggestion
                alt='landscape logos'
```

2024-10-18 17:07 UTC, DhairyaMajmudar commented on pages/tools/index.page.tsx
> +                    alt={''}
```suggestion
                    alt='adding your tool'
```

2024-10-18 17:07 UTC, DhairyaMajmudar commented on pages/tools/index.page.tsx
> +                    alt={''}
```suggestion
                    alt='try bowtie'
```

2024-10-18 17:14 UTC, DhairyaMajmudar commented on pages/index.page.tsx
> +          )}
I got you, no worries then keep the change 👍🏻

2024-10-22 19:31 UTC, DhairyaMajmudar commented
@29deepanshutyagi there are still some comments left to be resolved, can you pls. have a look on them

2024-10-30 15:03 UTC, DhairyaMajmudar commented on pages/index.page.tsx
@29deepanshutyagi alt texts are missing in file pls. add them.

2024-10-30 17:08 UTC, 29deepanshutyagi commented
kindly review it @benjagm

2024-11-11 13:54 UTC, DhairyaMajmudar requested changes
1. Images of case studies page is not as it was before

![image](https://github.com/user-attachments/assets/21d7e9e4-5310-461f-92cf-c22db30b55b9)

2. Sidebar Icons size is less as compare to before
 
![image](https://github.com/user-attachments/assets/c799a57f-8a01-43a9-864a-03ba51a1dc2d)

3. Tooling page icons size is decreased as compared to before

![image](https://github.com/user-attachments/assets/fcedbc21-8778-4882-8a3c-ab218e2fafac)

2024-11-15 13:36 UTC, 29deepanshutyagi commented
> @29deepanshutyagi Great progress!! just small fixes and we are good to go 🚀

but i had already set the width and height according to tailwind class there previously

2024-12-13 06:56 UTC, DhairyaMajmudar commented
Hi @29deepanshutyagi any progress on this? We're almost there just few changes left

2024-12-13 11:25 UTC, 29deepanshutyagi commented
> Hi @29deepanshutyagi any progress on this? We're almost there just few changes left

2024-12-22 18:47 UTC, heysujal commented
Hi @29deepanshutyagi , I cloned your repo to have a look what the conflicts are how to fix them.

You can follow below steps to resolve these conflicts.

1. Checkout to your `check` branch.
2. Run `git remote add upstream https://github.com/json-schema-org/website.git`
3. Run `git pull upstream main`
4. Use the souce control in VSCode
5. Accept Current change for `Card.tsx`
![image](https://github.com/user-attachments/assets/592a574a-7974-4d13-aa96-f3226df0617d)

Similarly you can do Accept Both option for `ToolingDetailModal.tsx`
![image](https://github.com/user-attachments/assets/08a4cf8c-5f7a-4d21-bbd4-48c0f97e5ee8)

After this you can stage all these merge changes(look for + icon in source control) and you can commit all the changes and push those changes like you usually do.

2024-12-22 19:15 UTC, closed without merging